Loading and preprocessing the data
----------------------------------

    # Load the data.

    activity <- read.csv("activity.csv", na.strings = "NA")

    # Process/transform the data (if necessary) into a format suitable for your analysis.

    str(activity)

    ## 'data.frame':    17568 obs. of  3 variables:
    ##  $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ date    : Factor w/ 61 levels "2012-10-01","2012-10-02",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...

    library(lubridate)

    ## 
    ## Attaching package: 'lubridate'

    ## The following object is masked from 'package:base':
    ## 
    ##     date

    activity$date <- ymd(activity$date)

    str(activity)

    ## 'data.frame':    17568 obs. of  3 variables:
    ##  $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ date    : Date, format: "2012-10-01" "2012-10-01" ...
    ##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...

    head(activity); tail(activity)

    ##   steps       date interval
    ## 1    NA 2012-10-01        0
    ## 2    NA 2012-10-01        5
    ## 3    NA 2012-10-01       10
    ## 4    NA 2012-10-01       15
    ## 5    NA 2012-10-01       20
    ## 6    NA 2012-10-01       25

    ##       steps       date interval
    ## 17563    NA 2012-11-30     2330
    ## 17564    NA 2012-11-30     2335
    ## 17565    NA 2012-11-30     2340
    ## 17566    NA 2012-11-30     2345
    ## 17567    NA 2012-11-30     2350
    ## 17568    NA 2012-11-30     2355

What is mean total number of steps taken per day?
-------------------------------------------------

    attach(activity)

    # Calculate the total number of steps taken per day.

    total_steps <- tapply(steps, date, sum, na.rm = TRUE)

    total_steps

    ## 2012-10-01 2012-10-02 2012-10-03 2012-10-04 2012-10-05 2012-10-06 
    ##          0        126      11352      12116      13294      15420 
    ## 2012-10-07 2012-10-08 2012-10-09 2012-10-10 2012-10-11 2012-10-12 
    ##      11015          0      12811       9900      10304      17382 
    ## 2012-10-13 2012-10-14 2012-10-15 2012-10-16 2012-10-17 2012-10-18 
    ##      12426      15098      10139      15084      13452      10056 
    ## 2012-10-19 2012-10-20 2012-10-21 2012-10-22 2012-10-23 2012-10-24 
    ##      11829      10395       8821      13460       8918       8355 
    ## 2012-10-25 2012-10-26 2012-10-27 2012-10-28 2012-10-29 2012-10-30 
    ##       2492       6778      10119      11458       5018       9819 
    ## 2012-10-31 2012-11-01 2012-11-02 2012-11-03 2012-11-04 2012-11-05 
    ##      15414          0      10600      10571          0      10439 
    ## 2012-11-06 2012-11-07 2012-11-08 2012-11-09 2012-11-10 2012-11-11 
    ##       8334      12883       3219          0          0      12608 
    ## 2012-11-12 2012-11-13 2012-11-14 2012-11-15 2012-11-16 2012-11-17 
    ##      10765       7336          0         41       5441      14339 
    ## 2012-11-18 2012-11-19 2012-11-20 2012-11-21 2012-11-22 2012-11-23 
    ##      15110       8841       4472      12787      20427      21194 
    ## 2012-11-24 2012-11-25 2012-11-26 2012-11-27 2012-11-28 2012-11-29 
    ##      14478      11834      11162      13646      10183       7047 
    ## 2012-11-30 
    ##          0

    # Make a histogram of the total number of steps taken each day.

    hist(total_steps, main = "Histogram of the Total Number of Steps Taken each Day", xlab = "Total number of steps taken each day")

<img src="PA1_template_files/figure-markdown_strict/unnamed-chunk-2-1.png" style="display: block; margin: auto;" />

    # Calculate and report the mean and the median of the total number of steps taken per day.

    summary(total_steps)

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##       0    6778   10400    9354   12810   21190

What is the average daily activity pattern?
-------------------------------------------

    # Make a time series plot of the 5-minute interval and the average number of steps taken.

    average_steps <- round(tapply(steps, interval, mean, na.rm = TRUE), digits = 2)

    average_steps

    ##      0      5     10     15     20     25     30     35     40     45 
    ##   1.72   0.34   0.13   0.15   0.08   2.09   0.53   0.87   0.00   1.47 
    ##     50     55    100    105    110    115    120    125    130    135 
    ##   0.30   0.13   0.32   0.68   0.15   0.34   0.00   1.11   1.83   0.17 
    ##    140    145    150    155    200    205    210    215    220    225 
    ##   0.17   0.38   0.26   0.00   0.00   0.00   1.13   0.00   0.00   0.13 
    ##    230    235    240    245    250    255    300    305    310    315 
    ##   0.00   0.23   0.00   0.00   1.55   0.94   0.00   0.00   0.00   0.00 
    ##    320    325    330    335    340    345    350    355    400    405 
    ##   0.21   0.62   1.62   0.58   0.49   0.08   0.00   0.00   1.19   0.94 
    ##    410    415    420    425    430    435    440    445    450    455 
    ##   2.57   0.00   0.34   0.36   4.11   0.66   3.49   0.83   3.11   1.11 
    ##    500    505    510    515    520    525    530    535    540    545 
    ##   0.00   1.57   3.00   2.25   3.32   2.96   2.09   6.06  16.02  18.34 
    ##    550    555    600    605    610    615    620    625    630    635 
    ##  39.45  44.49  31.49  49.26  53.77  63.45  49.96  47.08  52.15  39.34 
    ##    640    645    650    655    700    705    710    715    720    725 
    ##  44.02  44.17  37.36  49.04  43.81  44.38  50.51  54.51  49.92  50.98 
    ##    730    735    740    745    750    755    800    805    810    815 
    ##  55.68  44.32  52.26  69.55  57.85  56.15  73.38  68.21 129.43 157.53 
    ##    820    825    830    835    840    845    850    855    900    905 
    ## 171.15 155.40 177.30 206.17 195.92 179.57 183.40 167.02 143.45 124.04 
    ##    910    915    920    925    930    935    940    945    950    955 
    ## 109.11 108.11 103.72  95.96  66.21  45.23  24.79  38.75  34.98  21.06 
    ##   1000   1005   1010   1015   1020   1025   1030   1035   1040   1045 
    ##  40.57  26.98  42.42  52.66  38.92  50.79  44.28  37.42  34.70  28.34 
    ##   1050   1055   1100   1105   1110   1115   1120   1125   1130   1135 
    ##  25.09  31.94  31.36  29.68  21.32  25.55  28.38  26.47  33.43  49.98 
    ##   1140   1145   1150   1155   1200   1205   1210   1215   1220   1225 
    ##  42.04  44.60  46.04  59.19  63.87  87.70  94.85  92.77  63.40  50.17 
    ##   1230   1235   1240   1245   1250   1255   1300   1305   1310   1315 
    ##  54.47  32.42  26.53  37.74  45.06  67.28  42.34  39.89  43.26  40.98 
    ##   1320   1325   1330   1335   1340   1345   1350   1355   1400   1405 
    ##  46.25  56.43  42.75  25.13  39.96  53.55  47.32  60.81  55.75  51.96 
    ##   1410   1415   1420   1425   1430   1435   1440   1445   1450   1455 
    ##  43.58  48.70  35.47  37.55  41.85  27.51  17.11  26.08  43.62  43.77 
    ##   1500   1505   1510   1515   1520   1525   1530   1535   1540   1545 
    ##  30.02  36.08  35.49  38.85  45.96  47.75  48.13  65.32  82.91  98.66 
    ##   1550   1555   1600   1605   1610   1615   1620   1625   1630   1635 
    ## 102.11  83.96  62.13  64.13  74.55  63.17  56.91  59.77  43.87  38.57 
    ##   1640   1645   1650   1655   1700   1705   1710   1715   1720   1725 
    ##  44.66  45.45  46.21  43.68  46.62  56.30  50.72  61.23  72.72  78.94 
    ##   1730   1735   1740   1745   1750   1755   1800   1805   1810   1815 
    ##  68.94  59.66  75.09  56.51  34.77  37.45  40.68  58.02  74.70  85.32 
    ##   1820   1825   1830   1835   1840   1845   1850   1855   1900   1905 
    ##  59.26  67.77  77.70  74.25  85.34  99.45  86.58  85.60  84.87  77.83 
    ##   1910   1915   1920   1925   1930   1935   1940   1945   1950   1955 
    ##  58.04  53.36  36.32  20.72  27.40  40.02  30.21  25.55  45.66  33.53 
    ##   2000   2005   2010   2015   2020   2025   2030   2035   2040   2045 
    ##  19.62  19.02  19.34  33.34  26.81  21.17  27.30  21.34  19.55  21.32 
    ##   2050   2055   2100   2105   2110   2115   2120   2125   2130   2135 
    ##  32.30  20.15  15.94  17.23  23.45  19.25  12.45   8.02  14.66  16.30 
    ##   2140   2145   2150   2155   2200   2205   2210   2215   2220   2225 
    ##   8.68   7.79   8.13   2.62   1.45   3.68   4.81   8.51   7.08   8.70 
    ##   2230   2235   2240   2245   2250   2255   2300   2305   2310   2315 
    ##   9.75   2.21   0.32   0.11   1.60   4.60   3.30   2.85   0.00   0.83 
    ##   2320   2325   2330   2335   2340   2345   2350   2355 
    ##   0.96   1.58   2.60   4.70   3.30   0.64   0.23   1.08

    interval.f <- activity$interval

    interval.f <- unique(interval.f)

    interval.f

    ##   [1]    0    5   10   15   20   25   30   35   40   45   50   55  100  105
    ##  [15]  110  115  120  125  130  135  140  145  150  155  200  205  210  215
    ##  [29]  220  225  230  235  240  245  250  255  300  305  310  315  320  325
    ##  [43]  330  335  340  345  350  355  400  405  410  415  420  425  430  435
    ##  [57]  440  445  450  455  500  505  510  515  520  525  530  535  540  545
    ##  [71]  550  555  600  605  610  615  620  625  630  635  640  645  650  655
    ##  [85]  700  705  710  715  720  725  730  735  740  745  750  755  800  805
    ##  [99]  810  815  820  825  830  835  840  845  850  855  900  905  910  915
    ## [113]  920  925  930  935  940  945  950  955 1000 1005 1010 1015 1020 1025
    ## [127] 1030 1035 1040 1045 1050 1055 1100 1105 1110 1115 1120 1125 1130 1135
    ## [141] 1140 1145 1150 1155 1200 1205 1210 1215 1220 1225 1230 1235 1240 1245
    ## [155] 1250 1255 1300 1305 1310 1315 1320 1325 1330 1335 1340 1345 1350 1355
    ## [169] 1400 1405 1410 1415 1420 1425 1430 1435 1440 1445 1450 1455 1500 1505
    ## [183] 1510 1515 1520 1525 1530 1535 1540 1545 1550 1555 1600 1605 1610 1615
    ## [197] 1620 1625 1630 1635 1640 1645 1650 1655 1700 1705 1710 1715 1720 1725
    ## [211] 1730 1735 1740 1745 1750 1755 1800 1805 1810 1815 1820 1825 1830 1835
    ## [225] 1840 1845 1850 1855 1900 1905 1910 1915 1920 1925 1930 1935 1940 1945
    ## [239] 1950 1955 2000 2005 2010 2015 2020 2025 2030 2035 2040 2045 2050 2055
    ## [253] 2100 2105 2110 2115 2120 2125 2130 2135 2140 2145 2150 2155 2200 2205
    ## [267] 2210 2215 2220 2225 2230 2235 2240 2245 2250 2255 2300 2305 2310 2315
    ## [281] 2320 2325 2330 2335 2340 2345 2350 2355

    plot(interval.f, average_steps, type = "l", main = "Time Series Plot", xlab = "5-minute interval", ylab = "Average number of steps")

<img src="PA1_template_files/figure-markdown_strict/unnamed-chunk-3-1.png" style="display: block; margin: auto;" />

    # Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

    max(average_steps)

    ## [1] 206.17

    both <- data.frame(interval.f, average_steps)

    both[which.max(both$average_steps), ]

    ##     interval.f average_steps
    ## 835        835        206.17

Imputing missing values
-----------------------

    # Calculate and report the total number of missing values in the dataset.

    sum(is.na(activity))

    ## [1] 2304

    # Devise a strategy for filling in all of the missing values in the dataset.

    sum(is.na(steps))

    ## [1] 2304

    detach(activity)

    activity[!complete.cases(activity),]

    ##       steps       date interval
    ## 1        NA 2012-10-01        0
    ## 2        NA 2012-10-01        5
    ## 3        NA 2012-10-01       10
    ## 4        NA 2012-10-01       15
    ## 5        NA 2012-10-01       20
    ## 6        NA 2012-10-01       25
    ## 7        NA 2012-10-01       30
    ## 8        NA 2012-10-01       35
    ## 9        NA 2012-10-01       40
    ## 10       NA 2012-10-01       45
    ## 11       NA 2012-10-01       50
    ## 12       NA 2012-10-01       55
    ## 13       NA 2012-10-01      100
    ## 14       NA 2012-10-01      105
    ## 15       NA 2012-10-01      110
    ## 16       NA 2012-10-01      115
    ## 17       NA 2012-10-01      120
    ## 18       NA 2012-10-01      125
    ## 19       NA 2012-10-01      130
    ## 20       NA 2012-10-01      135
    ## 21       NA 2012-10-01      140
    ## 22       NA 2012-10-01      145
    ## 23       NA 2012-10-01      150
    ## 24       NA 2012-10-01      155
    ## 25       NA 2012-10-01      200
    ## 26       NA 2012-10-01      205
    ## 27       NA 2012-10-01      210
    ## 28       NA 2012-10-01      215
    ## 29       NA 2012-10-01      220
    ## 30       NA 2012-10-01      225
    ## 31       NA 2012-10-01      230
    ## 32       NA 2012-10-01      235
    ## 33       NA 2012-10-01      240
    ## 34       NA 2012-10-01      245
    ## 35       NA 2012-10-01      250
    ## 36       NA 2012-10-01      255
    ## 37       NA 2012-10-01      300
    ## 38       NA 2012-10-01      305
    ## 39       NA 2012-10-01      310
    ## 40       NA 2012-10-01      315
    ## 41       NA 2012-10-01      320
    ## 42       NA 2012-10-01      325
    ## 43       NA 2012-10-01      330
    ## 44       NA 2012-10-01      335
    ## 45       NA 2012-10-01      340
    ## 46       NA 2012-10-01      345
    ## 47       NA 2012-10-01      350
    ## 48       NA 2012-10-01      355
    ## 49       NA 2012-10-01      400
    ## 50       NA 2012-10-01      405
    ## 51       NA 2012-10-01      410
    ## 52       NA 2012-10-01      415
    ## 53       NA 2012-10-01      420
    ## 54       NA 2012-10-01      425
    ## 55       NA 2012-10-01      430
    ## 56       NA 2012-10-01      435
    ## 57       NA 2012-10-01      440
    ## 58       NA 2012-10-01      445
    ## 59       NA 2012-10-01      450
    ## 60       NA 2012-10-01      455
    ## 61       NA 2012-10-01      500
    ## 62       NA 2012-10-01      505
    ## 63       NA 2012-10-01      510
    ## 64       NA 2012-10-01      515
    ## 65       NA 2012-10-01      520
    ## 66       NA 2012-10-01      525
    ## 67       NA 2012-10-01      530
    ## 68       NA 2012-10-01      535
    ## 69       NA 2012-10-01      540
    ## 70       NA 2012-10-01      545
    ## 71       NA 2012-10-01      550
    ## 72       NA 2012-10-01      555
    ## 73       NA 2012-10-01      600
    ## 74       NA 2012-10-01      605
    ## 75       NA 2012-10-01      610
    ## 76       NA 2012-10-01      615
    ## 77       NA 2012-10-01      620
    ## 78       NA 2012-10-01      625
    ## 79       NA 2012-10-01      630
    ## 80       NA 2012-10-01      635
    ## 81       NA 2012-10-01      640
    ## 82       NA 2012-10-01      645
    ## 83       NA 2012-10-01      650
    ## 84       NA 2012-10-01      655
    ## 85       NA 2012-10-01      700
    ## 86       NA 2012-10-01      705
    ## 87       NA 2012-10-01      710
    ## 88       NA 2012-10-01      715
    ## 89       NA 2012-10-01      720
    ## 90       NA 2012-10-01      725
    ## 91       NA 2012-10-01      730
    ## 92       NA 2012-10-01      735
    ## 93       NA 2012-10-01      740
    ## 94       NA 2012-10-01      745
    ## 95       NA 2012-10-01      750
    ## 96       NA 2012-10-01      755
    ## 97       NA 2012-10-01      800
    ## 98       NA 2012-10-01      805
    ## 99       NA 2012-10-01      810
    ## 100      NA 2012-10-01      815
    ## 101      NA 2012-10-01      820
    ## 102      NA 2012-10-01      825
    ## 103      NA 2012-10-01      830
    ## 104      NA 2012-10-01      835
    ## 105      NA 2012-10-01      840
    ## 106      NA 2012-10-01      845
    ## 107      NA 2012-10-01      850
    ## 108      NA 2012-10-01      855
    ## 109      NA 2012-10-01      900
    ## 110      NA 2012-10-01      905
    ## 111      NA 2012-10-01      910
    ## 112      NA 2012-10-01      915
    ## 113      NA 2012-10-01      920
    ## 114      NA 2012-10-01      925
    ## 115      NA 2012-10-01      930
    ## 116      NA 2012-10-01      935
    ## 117      NA 2012-10-01      940
    ## 118      NA 2012-10-01      945
    ## 119      NA 2012-10-01      950
    ## 120      NA 2012-10-01      955
    ## 121      NA 2012-10-01     1000
    ## 122      NA 2012-10-01     1005
    ## 123      NA 2012-10-01     1010
    ## 124      NA 2012-10-01     1015
    ## 125      NA 2012-10-01     1020
    ## 126      NA 2012-10-01     1025
    ## 127      NA 2012-10-01     1030
    ## 128      NA 2012-10-01     1035
    ## 129      NA 2012-10-01     1040
    ## 130      NA 2012-10-01     1045
    ## 131      NA 2012-10-01     1050
    ## 132      NA 2012-10-01     1055
    ## 133      NA 2012-10-01     1100
    ## 134      NA 2012-10-01     1105
    ## 135      NA 2012-10-01     1110
    ## 136      NA 2012-10-01     1115
    ## 137      NA 2012-10-01     1120
    ## 138      NA 2012-10-01     1125
    ## 139      NA 2012-10-01     1130
    ## 140      NA 2012-10-01     1135
    ## 141      NA 2012-10-01     1140
    ## 142      NA 2012-10-01     1145
    ## 143      NA 2012-10-01     1150
    ## 144      NA 2012-10-01     1155
    ## 145      NA 2012-10-01     1200
    ## 146      NA 2012-10-01     1205
    ## 147      NA 2012-10-01     1210
    ## 148      NA 2012-10-01     1215
    ## 149      NA 2012-10-01     1220
    ## 150      NA 2012-10-01     1225
    ## 151      NA 2012-10-01     1230
    ## 152      NA 2012-10-01     1235
    ## 153      NA 2012-10-01     1240
    ## 154      NA 2012-10-01     1245
    ## 155      NA 2012-10-01     1250
    ## 156      NA 2012-10-01     1255
    ## 157      NA 2012-10-01     1300
    ## 158      NA 2012-10-01     1305
    ## 159      NA 2012-10-01     1310
    ## 160      NA 2012-10-01     1315
    ## 161      NA 2012-10-01     1320
    ## 162      NA 2012-10-01     1325
    ## 163      NA 2012-10-01     1330
    ## 164      NA 2012-10-01     1335
    ## 165      NA 2012-10-01     1340
    ## 166      NA 2012-10-01     1345
    ## 167      NA 2012-10-01     1350
    ## 168      NA 2012-10-01     1355
    ## 169      NA 2012-10-01     1400
    ## 170      NA 2012-10-01     1405
    ## 171      NA 2012-10-01     1410
    ## 172      NA 2012-10-01     1415
    ## 173      NA 2012-10-01     1420
    ## 174      NA 2012-10-01     1425
    ## 175      NA 2012-10-01     1430
    ## 176      NA 2012-10-01     1435
    ## 177      NA 2012-10-01     1440
    ## 178      NA 2012-10-01     1445
    ## 179      NA 2012-10-01     1450
    ## 180      NA 2012-10-01     1455
    ## 181      NA 2012-10-01     1500
    ## 182      NA 2012-10-01     1505
    ## 183      NA 2012-10-01     1510
    ## 184      NA 2012-10-01     1515
    ## 185      NA 2012-10-01     1520
    ## 186      NA 2012-10-01     1525
    ## 187      NA 2012-10-01     1530
    ## 188      NA 2012-10-01     1535
    ## 189      NA 2012-10-01     1540
    ## 190      NA 2012-10-01     1545
    ## 191      NA 2012-10-01     1550
    ## 192      NA 2012-10-01     1555
    ## 193      NA 2012-10-01     1600
    ## 194      NA 2012-10-01     1605
    ## 195      NA 2012-10-01     1610
    ## 196      NA 2012-10-01     1615
    ## 197      NA 2012-10-01     1620
    ## 198      NA 2012-10-01     1625
    ## 199      NA 2012-10-01     1630
    ## 200      NA 2012-10-01     1635
    ## 201      NA 2012-10-01     1640
    ## 202      NA 2012-10-01     1645
    ## 203      NA 2012-10-01     1650
    ## 204      NA 2012-10-01     1655
    ## 205      NA 2012-10-01     1700
    ## 206      NA 2012-10-01     1705
    ## 207      NA 2012-10-01     1710
    ## 208      NA 2012-10-01     1715
    ## 209      NA 2012-10-01     1720
    ## 210      NA 2012-10-01     1725
    ## 211      NA 2012-10-01     1730
    ## 212      NA 2012-10-01     1735
    ## 213      NA 2012-10-01     1740
    ## 214      NA 2012-10-01     1745
    ## 215      NA 2012-10-01     1750
    ## 216      NA 2012-10-01     1755
    ## 217      NA 2012-10-01     1800
    ## 218      NA 2012-10-01     1805
    ## 219      NA 2012-10-01     1810
    ## 220      NA 2012-10-01     1815
    ## 221      NA 2012-10-01     1820
    ## 222      NA 2012-10-01     1825
    ## 223      NA 2012-10-01     1830
    ## 224      NA 2012-10-01     1835
    ## 225      NA 2012-10-01     1840
    ## 226      NA 2012-10-01     1845
    ## 227      NA 2012-10-01     1850
    ## 228      NA 2012-10-01     1855
    ## 229      NA 2012-10-01     1900
    ## 230      NA 2012-10-01     1905
    ## 231      NA 2012-10-01     1910
    ## 232      NA 2012-10-01     1915
    ## 233      NA 2012-10-01     1920
    ## 234      NA 2012-10-01     1925
    ## 235      NA 2012-10-01     1930
    ## 236      NA 2012-10-01     1935
    ## 237      NA 2012-10-01     1940
    ## 238      NA 2012-10-01     1945
    ## 239      NA 2012-10-01     1950
    ## 240      NA 2012-10-01     1955
    ## 241      NA 2012-10-01     2000
    ## 242      NA 2012-10-01     2005
    ## 243      NA 2012-10-01     2010
    ## 244      NA 2012-10-01     2015
    ## 245      NA 2012-10-01     2020
    ## 246      NA 2012-10-01     2025
    ## 247      NA 2012-10-01     2030
    ## 248      NA 2012-10-01     2035
    ## 249      NA 2012-10-01     2040
    ## 250      NA 2012-10-01     2045
    ## 251      NA 2012-10-01     2050
    ## 252      NA 2012-10-01     2055
    ## 253      NA 2012-10-01     2100
    ## 254      NA 2012-10-01     2105
    ## 255      NA 2012-10-01     2110
    ## 256      NA 2012-10-01     2115
    ## 257      NA 2012-10-01     2120
    ## 258      NA 2012-10-01     2125
    ## 259      NA 2012-10-01     2130
    ## 260      NA 2012-10-01     2135
    ## 261      NA 2012-10-01     2140
    ## 262      NA 2012-10-01     2145
    ## 263      NA 2012-10-01     2150
    ## 264      NA 2012-10-01     2155
    ## 265      NA 2012-10-01     2200
    ## 266      NA 2012-10-01     2205
    ## 267      NA 2012-10-01     2210
    ## 268      NA 2012-10-01     2215
    ## 269      NA 2012-10-01     2220
    ## 270      NA 2012-10-01     2225
    ## 271      NA 2012-10-01     2230
    ## 272      NA 2012-10-01     2235
    ## 273      NA 2012-10-01     2240
    ## 274      NA 2012-10-01     2245
    ## 275      NA 2012-10-01     2250
    ## 276      NA 2012-10-01     2255
    ## 277      NA 2012-10-01     2300
    ## 278      NA 2012-10-01     2305
    ## 279      NA 2012-10-01     2310
    ## 280      NA 2012-10-01     2315
    ## 281      NA 2012-10-01     2320
    ## 282      NA 2012-10-01     2325
    ## 283      NA 2012-10-01     2330
    ## 284      NA 2012-10-01     2335
    ## 285      NA 2012-10-01     2340
    ## 286      NA 2012-10-01     2345
    ## 287      NA 2012-10-01     2350
    ## 288      NA 2012-10-01     2355
    ## 2017     NA 2012-10-08        0
    ## 2018     NA 2012-10-08        5
    ## 2019     NA 2012-10-08       10
    ## 2020     NA 2012-10-08       15
    ## 2021     NA 2012-10-08       20
    ## 2022     NA 2012-10-08       25
    ## 2023     NA 2012-10-08       30
    ## 2024     NA 2012-10-08       35
    ## 2025     NA 2012-10-08       40
    ## 2026     NA 2012-10-08       45
    ## 2027     NA 2012-10-08       50
    ## 2028     NA 2012-10-08       55
    ## 2029     NA 2012-10-08      100
    ## 2030     NA 2012-10-08      105
    ## 2031     NA 2012-10-08      110
    ## 2032     NA 2012-10-08      115
    ## 2033     NA 2012-10-08      120
    ## 2034     NA 2012-10-08      125
    ## 2035     NA 2012-10-08      130
    ## 2036     NA 2012-10-08      135
    ## 2037     NA 2012-10-08      140
    ## 2038     NA 2012-10-08      145
    ## 2039     NA 2012-10-08      150
    ## 2040     NA 2012-10-08      155
    ## 2041     NA 2012-10-08      200
    ## 2042     NA 2012-10-08      205
    ## 2043     NA 2012-10-08      210
    ## 2044     NA 2012-10-08      215
    ## 2045     NA 2012-10-08      220
    ## 2046     NA 2012-10-08      225
    ## 2047     NA 2012-10-08      230
    ## 2048     NA 2012-10-08      235
    ## 2049     NA 2012-10-08      240
    ## 2050     NA 2012-10-08      245
    ## 2051     NA 2012-10-08      250
    ## 2052     NA 2012-10-08      255
    ## 2053     NA 2012-10-08      300
    ## 2054     NA 2012-10-08      305
    ## 2055     NA 2012-10-08      310
    ## 2056     NA 2012-10-08      315
    ## 2057     NA 2012-10-08      320
    ## 2058     NA 2012-10-08      325
    ## 2059     NA 2012-10-08      330
    ## 2060     NA 2012-10-08      335
    ## 2061     NA 2012-10-08      340
    ## 2062     NA 2012-10-08      345
    ## 2063     NA 2012-10-08      350
    ## 2064     NA 2012-10-08      355
    ## 2065     NA 2012-10-08      400
    ## 2066     NA 2012-10-08      405
    ## 2067     NA 2012-10-08      410
    ## 2068     NA 2012-10-08      415
    ## 2069     NA 2012-10-08      420
    ## 2070     NA 2012-10-08      425
    ## 2071     NA 2012-10-08      430
    ## 2072     NA 2012-10-08      435
    ## 2073     NA 2012-10-08      440
    ## 2074     NA 2012-10-08      445
    ## 2075     NA 2012-10-08      450
    ## 2076     NA 2012-10-08      455
    ## 2077     NA 2012-10-08      500
    ## 2078     NA 2012-10-08      505
    ## 2079     NA 2012-10-08      510
    ## 2080     NA 2012-10-08      515
    ## 2081     NA 2012-10-08      520
    ## 2082     NA 2012-10-08      525
    ## 2083     NA 2012-10-08      530
    ## 2084     NA 2012-10-08      535
    ## 2085     NA 2012-10-08      540
    ## 2086     NA 2012-10-08      545
    ## 2087     NA 2012-10-08      550
    ## 2088     NA 2012-10-08      555
    ## 2089     NA 2012-10-08      600
    ## 2090     NA 2012-10-08      605
    ## 2091     NA 2012-10-08      610
    ## 2092     NA 2012-10-08      615
    ## 2093     NA 2012-10-08      620
    ## 2094     NA 2012-10-08      625
    ## 2095     NA 2012-10-08      630
    ## 2096     NA 2012-10-08      635
    ## 2097     NA 2012-10-08      640
    ## 2098     NA 2012-10-08      645
    ## 2099     NA 2012-10-08      650
    ## 2100     NA 2012-10-08      655
    ## 2101     NA 2012-10-08      700
    ## 2102     NA 2012-10-08      705
    ## 2103     NA 2012-10-08      710
    ## 2104     NA 2012-10-08      715
    ## 2105     NA 2012-10-08      720
    ## 2106     NA 2012-10-08      725
    ## 2107     NA 2012-10-08      730
    ## 2108     NA 2012-10-08      735
    ## 2109     NA 2012-10-08      740
    ## 2110     NA 2012-10-08      745
    ## 2111     NA 2012-10-08      750
    ## 2112     NA 2012-10-08      755
    ## 2113     NA 2012-10-08      800
    ## 2114     NA 2012-10-08      805
    ## 2115     NA 2012-10-08      810
    ## 2116     NA 2012-10-08      815
    ## 2117     NA 2012-10-08      820
    ## 2118     NA 2012-10-08      825
    ## 2119     NA 2012-10-08      830
    ## 2120     NA 2012-10-08      835
    ## 2121     NA 2012-10-08      840
    ## 2122     NA 2012-10-08      845
    ## 2123     NA 2012-10-08      850
    ## 2124     NA 2012-10-08      855
    ## 2125     NA 2012-10-08      900
    ## 2126     NA 2012-10-08      905
    ## 2127     NA 2012-10-08      910
    ## 2128     NA 2012-10-08      915
    ## 2129     NA 2012-10-08      920
    ## 2130     NA 2012-10-08      925
    ## 2131     NA 2012-10-08      930
    ## 2132     NA 2012-10-08      935
    ## 2133     NA 2012-10-08      940
    ## 2134     NA 2012-10-08      945
    ## 2135     NA 2012-10-08      950
    ## 2136     NA 2012-10-08      955
    ## 2137     NA 2012-10-08     1000
    ## 2138     NA 2012-10-08     1005
    ## 2139     NA 2012-10-08     1010
    ## 2140     NA 2012-10-08     1015
    ## 2141     NA 2012-10-08     1020
    ## 2142     NA 2012-10-08     1025
    ## 2143     NA 2012-10-08     1030
    ## 2144     NA 2012-10-08     1035
    ## 2145     NA 2012-10-08     1040
    ## 2146     NA 2012-10-08     1045
    ## 2147     NA 2012-10-08     1050
    ## 2148     NA 2012-10-08     1055
    ## 2149     NA 2012-10-08     1100
    ## 2150     NA 2012-10-08     1105
    ## 2151     NA 2012-10-08     1110
    ## 2152     NA 2012-10-08     1115
    ## 2153     NA 2012-10-08     1120
    ## 2154     NA 2012-10-08     1125
    ## 2155     NA 2012-10-08     1130
    ## 2156     NA 2012-10-08     1135
    ## 2157     NA 2012-10-08     1140
    ## 2158     NA 2012-10-08     1145
    ## 2159     NA 2012-10-08     1150
    ## 2160     NA 2012-10-08     1155
    ## 2161     NA 2012-10-08     1200
    ## 2162     NA 2012-10-08     1205
    ## 2163     NA 2012-10-08     1210
    ## 2164     NA 2012-10-08     1215
    ## 2165     NA 2012-10-08     1220
    ## 2166     NA 2012-10-08     1225
    ## 2167     NA 2012-10-08     1230
    ## 2168     NA 2012-10-08     1235
    ## 2169     NA 2012-10-08     1240
    ## 2170     NA 2012-10-08     1245
    ## 2171     NA 2012-10-08     1250
    ## 2172     NA 2012-10-08     1255
    ## 2173     NA 2012-10-08     1300
    ## 2174     NA 2012-10-08     1305
    ## 2175     NA 2012-10-08     1310
    ## 2176     NA 2012-10-08     1315
    ## 2177     NA 2012-10-08     1320
    ## 2178     NA 2012-10-08     1325
    ## 2179     NA 2012-10-08     1330
    ## 2180     NA 2012-10-08     1335
    ## 2181     NA 2012-10-08     1340
    ## 2182     NA 2012-10-08     1345
    ## 2183     NA 2012-10-08     1350
    ## 2184     NA 2012-10-08     1355
    ## 2185     NA 2012-10-08     1400
    ## 2186     NA 2012-10-08     1405
    ## 2187     NA 2012-10-08     1410
    ## 2188     NA 2012-10-08     1415
    ## 2189     NA 2012-10-08     1420
    ## 2190     NA 2012-10-08     1425
    ## 2191     NA 2012-10-08     1430
    ## 2192     NA 2012-10-08     1435
    ## 2193     NA 2012-10-08     1440
    ## 2194     NA 2012-10-08     1445
    ## 2195     NA 2012-10-08     1450
    ## 2196     NA 2012-10-08     1455
    ## 2197     NA 2012-10-08     1500
    ## 2198     NA 2012-10-08     1505
    ## 2199     NA 2012-10-08     1510
    ## 2200     NA 2012-10-08     1515
    ## 2201     NA 2012-10-08     1520
    ## 2202     NA 2012-10-08     1525
    ## 2203     NA 2012-10-08     1530
    ## 2204     NA 2012-10-08     1535
    ## 2205     NA 2012-10-08     1540
    ## 2206     NA 2012-10-08     1545
    ## 2207     NA 2012-10-08     1550
    ## 2208     NA 2012-10-08     1555
    ## 2209     NA 2012-10-08     1600
    ## 2210     NA 2012-10-08     1605
    ## 2211     NA 2012-10-08     1610
    ## 2212     NA 2012-10-08     1615
    ## 2213     NA 2012-10-08     1620
    ## 2214     NA 2012-10-08     1625
    ## 2215     NA 2012-10-08     1630
    ## 2216     NA 2012-10-08     1635
    ## 2217     NA 2012-10-08     1640
    ## 2218     NA 2012-10-08     1645
    ## 2219     NA 2012-10-08     1650
    ## 2220     NA 2012-10-08     1655
    ## 2221     NA 2012-10-08     1700
    ## 2222     NA 2012-10-08     1705
    ## 2223     NA 2012-10-08     1710
    ## 2224     NA 2012-10-08     1715
    ## 2225     NA 2012-10-08     1720
    ## 2226     NA 2012-10-08     1725
    ## 2227     NA 2012-10-08     1730
    ## 2228     NA 2012-10-08     1735
    ## 2229     NA 2012-10-08     1740
    ## 2230     NA 2012-10-08     1745
    ## 2231     NA 2012-10-08     1750
    ## 2232     NA 2012-10-08     1755
    ## 2233     NA 2012-10-08     1800
    ## 2234     NA 2012-10-08     1805
    ## 2235     NA 2012-10-08     1810
    ## 2236     NA 2012-10-08     1815
    ## 2237     NA 2012-10-08     1820
    ## 2238     NA 2012-10-08     1825
    ## 2239     NA 2012-10-08     1830
    ## 2240     NA 2012-10-08     1835
    ## 2241     NA 2012-10-08     1840
    ## 2242     NA 2012-10-08     1845
    ## 2243     NA 2012-10-08     1850
    ## 2244     NA 2012-10-08     1855
    ## 2245     NA 2012-10-08     1900
    ## 2246     NA 2012-10-08     1905
    ## 2247     NA 2012-10-08     1910
    ## 2248     NA 2012-10-08     1915
    ## 2249     NA 2012-10-08     1920
    ## 2250     NA 2012-10-08     1925
    ## 2251     NA 2012-10-08     1930
    ## 2252     NA 2012-10-08     1935
    ## 2253     NA 2012-10-08     1940
    ## 2254     NA 2012-10-08     1945
    ## 2255     NA 2012-10-08     1950
    ## 2256     NA 2012-10-08     1955
    ## 2257     NA 2012-10-08     2000
    ## 2258     NA 2012-10-08     2005
    ## 2259     NA 2012-10-08     2010
    ## 2260     NA 2012-10-08     2015
    ## 2261     NA 2012-10-08     2020
    ## 2262     NA 2012-10-08     2025
    ## 2263     NA 2012-10-08     2030
    ## 2264     NA 2012-10-08     2035
    ## 2265     NA 2012-10-08     2040
    ## 2266     NA 2012-10-08     2045
    ## 2267     NA 2012-10-08     2050
    ## 2268     NA 2012-10-08     2055
    ## 2269     NA 2012-10-08     2100
    ## 2270     NA 2012-10-08     2105
    ## 2271     NA 2012-10-08     2110
    ## 2272     NA 2012-10-08     2115
    ## 2273     NA 2012-10-08     2120
    ## 2274     NA 2012-10-08     2125
    ## 2275     NA 2012-10-08     2130
    ## 2276     NA 2012-10-08     2135
    ## 2277     NA 2012-10-08     2140
    ## 2278     NA 2012-10-08     2145
    ## 2279     NA 2012-10-08     2150
    ## 2280     NA 2012-10-08     2155
    ## 2281     NA 2012-10-08     2200
    ## 2282     NA 2012-10-08     2205
    ## 2283     NA 2012-10-08     2210
    ## 2284     NA 2012-10-08     2215
    ## 2285     NA 2012-10-08     2220
    ## 2286     NA 2012-10-08     2225
    ## 2287     NA 2012-10-08     2230
    ## 2288     NA 2012-10-08     2235
    ## 2289     NA 2012-10-08     2240
    ## 2290     NA 2012-10-08     2245
    ## 2291     NA 2012-10-08     2250
    ## 2292     NA 2012-10-08     2255
    ## 2293     NA 2012-10-08     2300
    ## 2294     NA 2012-10-08     2305
    ## 2295     NA 2012-10-08     2310
    ## 2296     NA 2012-10-08     2315
    ## 2297     NA 2012-10-08     2320
    ## 2298     NA 2012-10-08     2325
    ## 2299     NA 2012-10-08     2330
    ## 2300     NA 2012-10-08     2335
    ## 2301     NA 2012-10-08     2340
    ## 2302     NA 2012-10-08     2345
    ## 2303     NA 2012-10-08     2350
    ## 2304     NA 2012-10-08     2355
    ## 8929     NA 2012-11-01        0
    ## 8930     NA 2012-11-01        5
    ## 8931     NA 2012-11-01       10
    ## 8932     NA 2012-11-01       15
    ## 8933     NA 2012-11-01       20
    ## 8934     NA 2012-11-01       25
    ## 8935     NA 2012-11-01       30
    ## 8936     NA 2012-11-01       35
    ## 8937     NA 2012-11-01       40
    ## 8938     NA 2012-11-01       45
    ## 8939     NA 2012-11-01       50
    ## 8940     NA 2012-11-01       55
    ## 8941     NA 2012-11-01      100
    ## 8942     NA 2012-11-01      105
    ## 8943     NA 2012-11-01      110
    ## 8944     NA 2012-11-01      115
    ## 8945     NA 2012-11-01      120
    ## 8946     NA 2012-11-01      125
    ## 8947     NA 2012-11-01      130
    ## 8948     NA 2012-11-01      135
    ## 8949     NA 2012-11-01      140
    ## 8950     NA 2012-11-01      145
    ## 8951     NA 2012-11-01      150
    ## 8952     NA 2012-11-01      155
    ## 8953     NA 2012-11-01      200
    ## 8954     NA 2012-11-01      205
    ## 8955     NA 2012-11-01      210
    ## 8956     NA 2012-11-01      215
    ## 8957     NA 2012-11-01      220
    ## 8958     NA 2012-11-01      225
    ## 8959     NA 2012-11-01      230
    ## 8960     NA 2012-11-01      235
    ## 8961     NA 2012-11-01      240
    ## 8962     NA 2012-11-01      245
    ## 8963     NA 2012-11-01      250
    ## 8964     NA 2012-11-01      255
    ## 8965     NA 2012-11-01      300
    ## 8966     NA 2012-11-01      305
    ## 8967     NA 2012-11-01      310
    ## 8968     NA 2012-11-01      315
    ## 8969     NA 2012-11-01      320
    ## 8970     NA 2012-11-01      325
    ## 8971     NA 2012-11-01      330
    ## 8972     NA 2012-11-01      335
    ## 8973     NA 2012-11-01      340
    ## 8974     NA 2012-11-01      345
    ## 8975     NA 2012-11-01      350
    ## 8976     NA 2012-11-01      355
    ## 8977     NA 2012-11-01      400
    ## 8978     NA 2012-11-01      405
    ## 8979     NA 2012-11-01      410
    ## 8980     NA 2012-11-01      415
    ## 8981     NA 2012-11-01      420
    ## 8982     NA 2012-11-01      425
    ## 8983     NA 2012-11-01      430
    ## 8984     NA 2012-11-01      435
    ## 8985     NA 2012-11-01      440
    ## 8986     NA 2012-11-01      445
    ## 8987     NA 2012-11-01      450
    ## 8988     NA 2012-11-01      455
    ## 8989     NA 2012-11-01      500
    ## 8990     NA 2012-11-01      505
    ## 8991     NA 2012-11-01      510
    ## 8992     NA 2012-11-01      515
    ## 8993     NA 2012-11-01      520
    ## 8994     NA 2012-11-01      525
    ## 8995     NA 2012-11-01      530
    ## 8996     NA 2012-11-01      535
    ## 8997     NA 2012-11-01      540
    ## 8998     NA 2012-11-01      545
    ## 8999     NA 2012-11-01      550
    ## 9000     NA 2012-11-01      555
    ## 9001     NA 2012-11-01      600
    ## 9002     NA 2012-11-01      605
    ## 9003     NA 2012-11-01      610
    ## 9004     NA 2012-11-01      615
    ## 9005     NA 2012-11-01      620
    ## 9006     NA 2012-11-01      625
    ## 9007     NA 2012-11-01      630
    ## 9008     NA 2012-11-01      635
    ## 9009     NA 2012-11-01      640
    ## 9010     NA 2012-11-01      645
    ## 9011     NA 2012-11-01      650
    ## 9012     NA 2012-11-01      655
    ## 9013     NA 2012-11-01      700
    ## 9014     NA 2012-11-01      705
    ## 9015     NA 2012-11-01      710
    ## 9016     NA 2012-11-01      715
    ## 9017     NA 2012-11-01      720
    ## 9018     NA 2012-11-01      725
    ## 9019     NA 2012-11-01      730
    ## 9020     NA 2012-11-01      735
    ## 9021     NA 2012-11-01      740
    ## 9022     NA 2012-11-01      745
    ## 9023     NA 2012-11-01      750
    ## 9024     NA 2012-11-01      755
    ## 9025     NA 2012-11-01      800
    ## 9026     NA 2012-11-01      805
    ## 9027     NA 2012-11-01      810
    ## 9028     NA 2012-11-01      815
    ## 9029     NA 2012-11-01      820
    ## 9030     NA 2012-11-01      825
    ## 9031     NA 2012-11-01      830
    ## 9032     NA 2012-11-01      835
    ## 9033     NA 2012-11-01      840
    ## 9034     NA 2012-11-01      845
    ## 9035     NA 2012-11-01      850
    ## 9036     NA 2012-11-01      855
    ## 9037     NA 2012-11-01      900
    ## 9038     NA 2012-11-01      905
    ## 9039     NA 2012-11-01      910
    ## 9040     NA 2012-11-01      915
    ## 9041     NA 2012-11-01      920
    ## 9042     NA 2012-11-01      925
    ## 9043     NA 2012-11-01      930
    ## 9044     NA 2012-11-01      935
    ## 9045     NA 2012-11-01      940
    ## 9046     NA 2012-11-01      945
    ## 9047     NA 2012-11-01      950
    ## 9048     NA 2012-11-01      955
    ## 9049     NA 2012-11-01     1000
    ## 9050     NA 2012-11-01     1005
    ## 9051     NA 2012-11-01     1010
    ## 9052     NA 2012-11-01     1015
    ## 9053     NA 2012-11-01     1020
    ## 9054     NA 2012-11-01     1025
    ## 9055     NA 2012-11-01     1030
    ## 9056     NA 2012-11-01     1035
    ## 9057     NA 2012-11-01     1040
    ## 9058     NA 2012-11-01     1045
    ## 9059     NA 2012-11-01     1050
    ## 9060     NA 2012-11-01     1055
    ## 9061     NA 2012-11-01     1100
    ## 9062     NA 2012-11-01     1105
    ## 9063     NA 2012-11-01     1110
    ## 9064     NA 2012-11-01     1115
    ## 9065     NA 2012-11-01     1120
    ## 9066     NA 2012-11-01     1125
    ## 9067     NA 2012-11-01     1130
    ## 9068     NA 2012-11-01     1135
    ## 9069     NA 2012-11-01     1140
    ## 9070     NA 2012-11-01     1145
    ## 9071     NA 2012-11-01     1150
    ## 9072     NA 2012-11-01     1155
    ## 9073     NA 2012-11-01     1200
    ## 9074     NA 2012-11-01     1205
    ## 9075     NA 2012-11-01     1210
    ## 9076     NA 2012-11-01     1215
    ## 9077     NA 2012-11-01     1220
    ## 9078     NA 2012-11-01     1225
    ## 9079     NA 2012-11-01     1230
    ## 9080     NA 2012-11-01     1235
    ## 9081     NA 2012-11-01     1240
    ## 9082     NA 2012-11-01     1245
    ## 9083     NA 2012-11-01     1250
    ## 9084     NA 2012-11-01     1255
    ## 9085     NA 2012-11-01     1300
    ## 9086     NA 2012-11-01     1305
    ## 9087     NA 2012-11-01     1310
    ## 9088     NA 2012-11-01     1315
    ## 9089     NA 2012-11-01     1320
    ## 9090     NA 2012-11-01     1325
    ## 9091     NA 2012-11-01     1330
    ## 9092     NA 2012-11-01     1335
    ## 9093     NA 2012-11-01     1340
    ## 9094     NA 2012-11-01     1345
    ## 9095     NA 2012-11-01     1350
    ## 9096     NA 2012-11-01     1355
    ## 9097     NA 2012-11-01     1400
    ## 9098     NA 2012-11-01     1405
    ## 9099     NA 2012-11-01     1410
    ## 9100     NA 2012-11-01     1415
    ## 9101     NA 2012-11-01     1420
    ## 9102     NA 2012-11-01     1425
    ## 9103     NA 2012-11-01     1430
    ## 9104     NA 2012-11-01     1435
    ## 9105     NA 2012-11-01     1440
    ## 9106     NA 2012-11-01     1445
    ## 9107     NA 2012-11-01     1450
    ## 9108     NA 2012-11-01     1455
    ## 9109     NA 2012-11-01     1500
    ## 9110     NA 2012-11-01     1505
    ## 9111     NA 2012-11-01     1510
    ## 9112     NA 2012-11-01     1515
    ## 9113     NA 2012-11-01     1520
    ## 9114     NA 2012-11-01     1525
    ## 9115     NA 2012-11-01     1530
    ## 9116     NA 2012-11-01     1535
    ## 9117     NA 2012-11-01     1540
    ## 9118     NA 2012-11-01     1545
    ## 9119     NA 2012-11-01     1550
    ## 9120     NA 2012-11-01     1555
    ## 9121     NA 2012-11-01     1600
    ## 9122     NA 2012-11-01     1605
    ## 9123     NA 2012-11-01     1610
    ## 9124     NA 2012-11-01     1615
    ## 9125     NA 2012-11-01     1620
    ## 9126     NA 2012-11-01     1625
    ## 9127     NA 2012-11-01     1630
    ## 9128     NA 2012-11-01     1635
    ## 9129     NA 2012-11-01     1640
    ## 9130     NA 2012-11-01     1645
    ## 9131     NA 2012-11-01     1650
    ## 9132     NA 2012-11-01     1655
    ## 9133     NA 2012-11-01     1700
    ## 9134     NA 2012-11-01     1705
    ## 9135     NA 2012-11-01     1710
    ## 9136     NA 2012-11-01     1715
    ## 9137     NA 2012-11-01     1720
    ## 9138     NA 2012-11-01     1725
    ## 9139     NA 2012-11-01     1730
    ## 9140     NA 2012-11-01     1735
    ## 9141     NA 2012-11-01     1740
    ## 9142     NA 2012-11-01     1745
    ## 9143     NA 2012-11-01     1750
    ## 9144     NA 2012-11-01     1755
    ## 9145     NA 2012-11-01     1800
    ## 9146     NA 2012-11-01     1805
    ## 9147     NA 2012-11-01     1810
    ## 9148     NA 2012-11-01     1815
    ## 9149     NA 2012-11-01     1820
    ## 9150     NA 2012-11-01     1825
    ## 9151     NA 2012-11-01     1830
    ## 9152     NA 2012-11-01     1835
    ## 9153     NA 2012-11-01     1840
    ## 9154     NA 2012-11-01     1845
    ## 9155     NA 2012-11-01     1850
    ## 9156     NA 2012-11-01     1855
    ## 9157     NA 2012-11-01     1900
    ## 9158     NA 2012-11-01     1905
    ## 9159     NA 2012-11-01     1910
    ## 9160     NA 2012-11-01     1915
    ## 9161     NA 2012-11-01     1920
    ## 9162     NA 2012-11-01     1925
    ## 9163     NA 2012-11-01     1930
    ## 9164     NA 2012-11-01     1935
    ## 9165     NA 2012-11-01     1940
    ## 9166     NA 2012-11-01     1945
    ## 9167     NA 2012-11-01     1950
    ## 9168     NA 2012-11-01     1955
    ## 9169     NA 2012-11-01     2000
    ## 9170     NA 2012-11-01     2005
    ## 9171     NA 2012-11-01     2010
    ## 9172     NA 2012-11-01     2015
    ## 9173     NA 2012-11-01     2020
    ## 9174     NA 2012-11-01     2025
    ## 9175     NA 2012-11-01     2030
    ## 9176     NA 2012-11-01     2035
    ## 9177     NA 2012-11-01     2040
    ## 9178     NA 2012-11-01     2045
    ## 9179     NA 2012-11-01     2050
    ## 9180     NA 2012-11-01     2055
    ## 9181     NA 2012-11-01     2100
    ## 9182     NA 2012-11-01     2105
    ## 9183     NA 2012-11-01     2110
    ## 9184     NA 2012-11-01     2115
    ## 9185     NA 2012-11-01     2120
    ## 9186     NA 2012-11-01     2125
    ## 9187     NA 2012-11-01     2130
    ## 9188     NA 2012-11-01     2135
    ## 9189     NA 2012-11-01     2140
    ## 9190     NA 2012-11-01     2145
    ## 9191     NA 2012-11-01     2150
    ## 9192     NA 2012-11-01     2155
    ## 9193     NA 2012-11-01     2200
    ## 9194     NA 2012-11-01     2205
    ## 9195     NA 2012-11-01     2210
    ## 9196     NA 2012-11-01     2215
    ## 9197     NA 2012-11-01     2220
    ## 9198     NA 2012-11-01     2225
    ## 9199     NA 2012-11-01     2230
    ## 9200     NA 2012-11-01     2235
    ## 9201     NA 2012-11-01     2240
    ## 9202     NA 2012-11-01     2245
    ## 9203     NA 2012-11-01     2250
    ## 9204     NA 2012-11-01     2255
    ## 9205     NA 2012-11-01     2300
    ## 9206     NA 2012-11-01     2305
    ## 9207     NA 2012-11-01     2310
    ## 9208     NA 2012-11-01     2315
    ## 9209     NA 2012-11-01     2320
    ## 9210     NA 2012-11-01     2325
    ## 9211     NA 2012-11-01     2330
    ## 9212     NA 2012-11-01     2335
    ## 9213     NA 2012-11-01     2340
    ## 9214     NA 2012-11-01     2345
    ## 9215     NA 2012-11-01     2350
    ## 9216     NA 2012-11-01     2355
    ## 9793     NA 2012-11-04        0
    ## 9794     NA 2012-11-04        5
    ## 9795     NA 2012-11-04       10
    ## 9796     NA 2012-11-04       15
    ## 9797     NA 2012-11-04       20
    ## 9798     NA 2012-11-04       25
    ## 9799     NA 2012-11-04       30
    ## 9800     NA 2012-11-04       35
    ## 9801     NA 2012-11-04       40
    ## 9802     NA 2012-11-04       45
    ## 9803     NA 2012-11-04       50
    ## 9804     NA 2012-11-04       55
    ## 9805     NA 2012-11-04      100
    ## 9806     NA 2012-11-04      105
    ## 9807     NA 2012-11-04      110
    ## 9808     NA 2012-11-04      115
    ## 9809     NA 2012-11-04      120
    ## 9810     NA 2012-11-04      125
    ## 9811     NA 2012-11-04      130
    ## 9812     NA 2012-11-04      135
    ## 9813     NA 2012-11-04      140
    ## 9814     NA 2012-11-04      145
    ## 9815     NA 2012-11-04      150
    ## 9816     NA 2012-11-04      155
    ## 9817     NA 2012-11-04      200
    ## 9818     NA 2012-11-04      205
    ## 9819     NA 2012-11-04      210
    ## 9820     NA 2012-11-04      215
    ## 9821     NA 2012-11-04      220
    ## 9822     NA 2012-11-04      225
    ## 9823     NA 2012-11-04      230
    ## 9824     NA 2012-11-04      235
    ## 9825     NA 2012-11-04      240
    ## 9826     NA 2012-11-04      245
    ## 9827     NA 2012-11-04      250
    ## 9828     NA 2012-11-04      255
    ## 9829     NA 2012-11-04      300
    ## 9830     NA 2012-11-04      305
    ## 9831     NA 2012-11-04      310
    ## 9832     NA 2012-11-04      315
    ## 9833     NA 2012-11-04      320
    ## 9834     NA 2012-11-04      325
    ## 9835     NA 2012-11-04      330
    ## 9836     NA 2012-11-04      335
    ## 9837     NA 2012-11-04      340
    ## 9838     NA 2012-11-04      345
    ## 9839     NA 2012-11-04      350
    ## 9840     NA 2012-11-04      355
    ## 9841     NA 2012-11-04      400
    ## 9842     NA 2012-11-04      405
    ## 9843     NA 2012-11-04      410
    ## 9844     NA 2012-11-04      415
    ## 9845     NA 2012-11-04      420
    ## 9846     NA 2012-11-04      425
    ## 9847     NA 2012-11-04      430
    ## 9848     NA 2012-11-04      435
    ## 9849     NA 2012-11-04      440
    ## 9850     NA 2012-11-04      445
    ## 9851     NA 2012-11-04      450
    ## 9852     NA 2012-11-04      455
    ## 9853     NA 2012-11-04      500
    ## 9854     NA 2012-11-04      505
    ## 9855     NA 2012-11-04      510
    ## 9856     NA 2012-11-04      515
    ## 9857     NA 2012-11-04      520
    ## 9858     NA 2012-11-04      525
    ## 9859     NA 2012-11-04      530
    ## 9860     NA 2012-11-04      535
    ## 9861     NA 2012-11-04      540
    ## 9862     NA 2012-11-04      545
    ## 9863     NA 2012-11-04      550
    ## 9864     NA 2012-11-04      555
    ## 9865     NA 2012-11-04      600
    ## 9866     NA 2012-11-04      605
    ## 9867     NA 2012-11-04      610
    ## 9868     NA 2012-11-04      615
    ## 9869     NA 2012-11-04      620
    ## 9870     NA 2012-11-04      625
    ## 9871     NA 2012-11-04      630
    ## 9872     NA 2012-11-04      635
    ## 9873     NA 2012-11-04      640
    ## 9874     NA 2012-11-04      645
    ## 9875     NA 2012-11-04      650
    ## 9876     NA 2012-11-04      655
    ## 9877     NA 2012-11-04      700
    ## 9878     NA 2012-11-04      705
    ## 9879     NA 2012-11-04      710
    ## 9880     NA 2012-11-04      715
    ## 9881     NA 2012-11-04      720
    ## 9882     NA 2012-11-04      725
    ## 9883     NA 2012-11-04      730
    ## 9884     NA 2012-11-04      735
    ## 9885     NA 2012-11-04      740
    ## 9886     NA 2012-11-04      745
    ## 9887     NA 2012-11-04      750
    ## 9888     NA 2012-11-04      755
    ## 9889     NA 2012-11-04      800
    ## 9890     NA 2012-11-04      805
    ## 9891     NA 2012-11-04      810
    ## 9892     NA 2012-11-04      815
    ## 9893     NA 2012-11-04      820
    ## 9894     NA 2012-11-04      825
    ## 9895     NA 2012-11-04      830
    ## 9896     NA 2012-11-04      835
    ## 9897     NA 2012-11-04      840
    ## 9898     NA 2012-11-04      845
    ## 9899     NA 2012-11-04      850
    ## 9900     NA 2012-11-04      855
    ## 9901     NA 2012-11-04      900
    ## 9902     NA 2012-11-04      905
    ## 9903     NA 2012-11-04      910
    ## 9904     NA 2012-11-04      915
    ## 9905     NA 2012-11-04      920
    ## 9906     NA 2012-11-04      925
    ## 9907     NA 2012-11-04      930
    ## 9908     NA 2012-11-04      935
    ## 9909     NA 2012-11-04      940
    ## 9910     NA 2012-11-04      945
    ## 9911     NA 2012-11-04      950
    ## 9912     NA 2012-11-04      955
    ## 9913     NA 2012-11-04     1000
    ## 9914     NA 2012-11-04     1005
    ## 9915     NA 2012-11-04     1010
    ## 9916     NA 2012-11-04     1015
    ## 9917     NA 2012-11-04     1020
    ## 9918     NA 2012-11-04     1025
    ## 9919     NA 2012-11-04     1030
    ## 9920     NA 2012-11-04     1035
    ## 9921     NA 2012-11-04     1040
    ## 9922     NA 2012-11-04     1045
    ## 9923     NA 2012-11-04     1050
    ## 9924     NA 2012-11-04     1055
    ## 9925     NA 2012-11-04     1100
    ## 9926     NA 2012-11-04     1105
    ## 9927     NA 2012-11-04     1110
    ## 9928     NA 2012-11-04     1115
    ## 9929     NA 2012-11-04     1120
    ## 9930     NA 2012-11-04     1125
    ## 9931     NA 2012-11-04     1130
    ## 9932     NA 2012-11-04     1135
    ## 9933     NA 2012-11-04     1140
    ## 9934     NA 2012-11-04     1145
    ## 9935     NA 2012-11-04     1150
    ## 9936     NA 2012-11-04     1155
    ## 9937     NA 2012-11-04     1200
    ## 9938     NA 2012-11-04     1205
    ## 9939     NA 2012-11-04     1210
    ## 9940     NA 2012-11-04     1215
    ## 9941     NA 2012-11-04     1220
    ## 9942     NA 2012-11-04     1225
    ## 9943     NA 2012-11-04     1230
    ## 9944     NA 2012-11-04     1235
    ## 9945     NA 2012-11-04     1240
    ## 9946     NA 2012-11-04     1245
    ## 9947     NA 2012-11-04     1250
    ## 9948     NA 2012-11-04     1255
    ## 9949     NA 2012-11-04     1300
    ## 9950     NA 2012-11-04     1305
    ## 9951     NA 2012-11-04     1310
    ## 9952     NA 2012-11-04     1315
    ## 9953     NA 2012-11-04     1320
    ## 9954     NA 2012-11-04     1325
    ## 9955     NA 2012-11-04     1330
    ## 9956     NA 2012-11-04     1335
    ## 9957     NA 2012-11-04     1340
    ## 9958     NA 2012-11-04     1345
    ## 9959     NA 2012-11-04     1350
    ## 9960     NA 2012-11-04     1355
    ## 9961     NA 2012-11-04     1400
    ## 9962     NA 2012-11-04     1405
    ## 9963     NA 2012-11-04     1410
    ## 9964     NA 2012-11-04     1415
    ## 9965     NA 2012-11-04     1420
    ## 9966     NA 2012-11-04     1425
    ## 9967     NA 2012-11-04     1430
    ## 9968     NA 2012-11-04     1435
    ## 9969     NA 2012-11-04     1440
    ## 9970     NA 2012-11-04     1445
    ## 9971     NA 2012-11-04     1450
    ## 9972     NA 2012-11-04     1455
    ## 9973     NA 2012-11-04     1500
    ## 9974     NA 2012-11-04     1505
    ## 9975     NA 2012-11-04     1510
    ## 9976     NA 2012-11-04     1515
    ## 9977     NA 2012-11-04     1520
    ## 9978     NA 2012-11-04     1525
    ## 9979     NA 2012-11-04     1530
    ## 9980     NA 2012-11-04     1535
    ## 9981     NA 2012-11-04     1540
    ## 9982     NA 2012-11-04     1545
    ## 9983     NA 2012-11-04     1550
    ## 9984     NA 2012-11-04     1555
    ## 9985     NA 2012-11-04     1600
    ## 9986     NA 2012-11-04     1605
    ## 9987     NA 2012-11-04     1610
    ## 9988     NA 2012-11-04     1615
    ## 9989     NA 2012-11-04     1620
    ## 9990     NA 2012-11-04     1625
    ## 9991     NA 2012-11-04     1630
    ## 9992     NA 2012-11-04     1635
    ## 9993     NA 2012-11-04     1640
    ## 9994     NA 2012-11-04     1645
    ## 9995     NA 2012-11-04     1650
    ## 9996     NA 2012-11-04     1655
    ## 9997     NA 2012-11-04     1700
    ## 9998     NA 2012-11-04     1705
    ## 9999     NA 2012-11-04     1710
    ## 10000    NA 2012-11-04     1715
    ## 10001    NA 2012-11-04     1720
    ## 10002    NA 2012-11-04     1725
    ## 10003    NA 2012-11-04     1730
    ## 10004    NA 2012-11-04     1735
    ## 10005    NA 2012-11-04     1740
    ## 10006    NA 2012-11-04     1745
    ## 10007    NA 2012-11-04     1750
    ## 10008    NA 2012-11-04     1755
    ## 10009    NA 2012-11-04     1800
    ## 10010    NA 2012-11-04     1805
    ## 10011    NA 2012-11-04     1810
    ## 10012    NA 2012-11-04     1815
    ## 10013    NA 2012-11-04     1820
    ## 10014    NA 2012-11-04     1825
    ## 10015    NA 2012-11-04     1830
    ## 10016    NA 2012-11-04     1835
    ## 10017    NA 2012-11-04     1840
    ## 10018    NA 2012-11-04     1845
    ## 10019    NA 2012-11-04     1850
    ## 10020    NA 2012-11-04     1855
    ## 10021    NA 2012-11-04     1900
    ## 10022    NA 2012-11-04     1905
    ## 10023    NA 2012-11-04     1910
    ## 10024    NA 2012-11-04     1915
    ## 10025    NA 2012-11-04     1920
    ## 10026    NA 2012-11-04     1925
    ## 10027    NA 2012-11-04     1930
    ## 10028    NA 2012-11-04     1935
    ## 10029    NA 2012-11-04     1940
    ## 10030    NA 2012-11-04     1945
    ## 10031    NA 2012-11-04     1950
    ## 10032    NA 2012-11-04     1955
    ## 10033    NA 2012-11-04     2000
    ## 10034    NA 2012-11-04     2005
    ## 10035    NA 2012-11-04     2010
    ## 10036    NA 2012-11-04     2015
    ## 10037    NA 2012-11-04     2020
    ## 10038    NA 2012-11-04     2025
    ## 10039    NA 2012-11-04     2030
    ## 10040    NA 2012-11-04     2035
    ## 10041    NA 2012-11-04     2040
    ## 10042    NA 2012-11-04     2045
    ## 10043    NA 2012-11-04     2050
    ## 10044    NA 2012-11-04     2055
    ## 10045    NA 2012-11-04     2100
    ## 10046    NA 2012-11-04     2105
    ## 10047    NA 2012-11-04     2110
    ## 10048    NA 2012-11-04     2115
    ## 10049    NA 2012-11-04     2120
    ## 10050    NA 2012-11-04     2125
    ## 10051    NA 2012-11-04     2130
    ## 10052    NA 2012-11-04     2135
    ## 10053    NA 2012-11-04     2140
    ## 10054    NA 2012-11-04     2145
    ## 10055    NA 2012-11-04     2150
    ## 10056    NA 2012-11-04     2155
    ## 10057    NA 2012-11-04     2200
    ## 10058    NA 2012-11-04     2205
    ## 10059    NA 2012-11-04     2210
    ## 10060    NA 2012-11-04     2215
    ## 10061    NA 2012-11-04     2220
    ## 10062    NA 2012-11-04     2225
    ## 10063    NA 2012-11-04     2230
    ## 10064    NA 2012-11-04     2235
    ## 10065    NA 2012-11-04     2240
    ## 10066    NA 2012-11-04     2245
    ## 10067    NA 2012-11-04     2250
    ## 10068    NA 2012-11-04     2255
    ## 10069    NA 2012-11-04     2300
    ## 10070    NA 2012-11-04     2305
    ## 10071    NA 2012-11-04     2310
    ## 10072    NA 2012-11-04     2315
    ## 10073    NA 2012-11-04     2320
    ## 10074    NA 2012-11-04     2325
    ## 10075    NA 2012-11-04     2330
    ## 10076    NA 2012-11-04     2335
    ## 10077    NA 2012-11-04     2340
    ## 10078    NA 2012-11-04     2345
    ## 10079    NA 2012-11-04     2350
    ## 10080    NA 2012-11-04     2355
    ## 11233    NA 2012-11-09        0
    ## 11234    NA 2012-11-09        5
    ## 11235    NA 2012-11-09       10
    ## 11236    NA 2012-11-09       15
    ## 11237    NA 2012-11-09       20
    ## 11238    NA 2012-11-09       25
    ## 11239    NA 2012-11-09       30
    ## 11240    NA 2012-11-09       35
    ## 11241    NA 2012-11-09       40
    ## 11242    NA 2012-11-09       45
    ## 11243    NA 2012-11-09       50
    ## 11244    NA 2012-11-09       55
    ## 11245    NA 2012-11-09      100
    ## 11246    NA 2012-11-09      105
    ## 11247    NA 2012-11-09      110
    ## 11248    NA 2012-11-09      115
    ## 11249    NA 2012-11-09      120
    ## 11250    NA 2012-11-09      125
    ## 11251    NA 2012-11-09      130
    ## 11252    NA 2012-11-09      135
    ## 11253    NA 2012-11-09      140
    ## 11254    NA 2012-11-09      145
    ## 11255    NA 2012-11-09      150
    ## 11256    NA 2012-11-09      155
    ## 11257    NA 2012-11-09      200
    ## 11258    NA 2012-11-09      205
    ## 11259    NA 2012-11-09      210
    ## 11260    NA 2012-11-09      215
    ## 11261    NA 2012-11-09      220
    ## 11262    NA 2012-11-09      225
    ## 11263    NA 2012-11-09      230
    ## 11264    NA 2012-11-09      235
    ## 11265    NA 2012-11-09      240
    ## 11266    NA 2012-11-09      245
    ## 11267    NA 2012-11-09      250
    ## 11268    NA 2012-11-09      255
    ## 11269    NA 2012-11-09      300
    ## 11270    NA 2012-11-09      305
    ## 11271    NA 2012-11-09      310
    ## 11272    NA 2012-11-09      315
    ## 11273    NA 2012-11-09      320
    ## 11274    NA 2012-11-09      325
    ## 11275    NA 2012-11-09      330
    ## 11276    NA 2012-11-09      335
    ## 11277    NA 2012-11-09      340
    ## 11278    NA 2012-11-09      345
    ## 11279    NA 2012-11-09      350
    ## 11280    NA 2012-11-09      355
    ## 11281    NA 2012-11-09      400
    ## 11282    NA 2012-11-09      405
    ## 11283    NA 2012-11-09      410
    ## 11284    NA 2012-11-09      415
    ## 11285    NA 2012-11-09      420
    ## 11286    NA 2012-11-09      425
    ## 11287    NA 2012-11-09      430
    ## 11288    NA 2012-11-09      435
    ## 11289    NA 2012-11-09      440
    ## 11290    NA 2012-11-09      445
    ## 11291    NA 2012-11-09      450
    ## 11292    NA 2012-11-09      455
    ## 11293    NA 2012-11-09      500
    ## 11294    NA 2012-11-09      505
    ## 11295    NA 2012-11-09      510
    ## 11296    NA 2012-11-09      515
    ## 11297    NA 2012-11-09      520
    ## 11298    NA 2012-11-09      525
    ## 11299    NA 2012-11-09      530
    ## 11300    NA 2012-11-09      535
    ## 11301    NA 2012-11-09      540
    ## 11302    NA 2012-11-09      545
    ## 11303    NA 2012-11-09      550
    ## 11304    NA 2012-11-09      555
    ## 11305    NA 2012-11-09      600
    ## 11306    NA 2012-11-09      605
    ## 11307    NA 2012-11-09      610
    ## 11308    NA 2012-11-09      615
    ## 11309    NA 2012-11-09      620
    ## 11310    NA 2012-11-09      625
    ## 11311    NA 2012-11-09      630
    ## 11312    NA 2012-11-09      635
    ## 11313    NA 2012-11-09      640
    ## 11314    NA 2012-11-09      645
    ## 11315    NA 2012-11-09      650
    ## 11316    NA 2012-11-09      655
    ## 11317    NA 2012-11-09      700
    ## 11318    NA 2012-11-09      705
    ## 11319    NA 2012-11-09      710
    ## 11320    NA 2012-11-09      715
    ## 11321    NA 2012-11-09      720
    ## 11322    NA 2012-11-09      725
    ## 11323    NA 2012-11-09      730
    ## 11324    NA 2012-11-09      735
    ## 11325    NA 2012-11-09      740
    ## 11326    NA 2012-11-09      745
    ## 11327    NA 2012-11-09      750
    ## 11328    NA 2012-11-09      755
    ## 11329    NA 2012-11-09      800
    ## 11330    NA 2012-11-09      805
    ## 11331    NA 2012-11-09      810
    ## 11332    NA 2012-11-09      815
    ## 11333    NA 2012-11-09      820
    ## 11334    NA 2012-11-09      825
    ## 11335    NA 2012-11-09      830
    ## 11336    NA 2012-11-09      835
    ## 11337    NA 2012-11-09      840
    ## 11338    NA 2012-11-09      845
    ## 11339    NA 2012-11-09      850
    ## 11340    NA 2012-11-09      855
    ## 11341    NA 2012-11-09      900
    ## 11342    NA 2012-11-09      905
    ## 11343    NA 2012-11-09      910
    ## 11344    NA 2012-11-09      915
    ## 11345    NA 2012-11-09      920
    ## 11346    NA 2012-11-09      925
    ## 11347    NA 2012-11-09      930
    ## 11348    NA 2012-11-09      935
    ## 11349    NA 2012-11-09      940
    ## 11350    NA 2012-11-09      945
    ## 11351    NA 2012-11-09      950
    ## 11352    NA 2012-11-09      955
    ## 11353    NA 2012-11-09     1000
    ## 11354    NA 2012-11-09     1005
    ## 11355    NA 2012-11-09     1010
    ## 11356    NA 2012-11-09     1015
    ## 11357    NA 2012-11-09     1020
    ## 11358    NA 2012-11-09     1025
    ## 11359    NA 2012-11-09     1030
    ## 11360    NA 2012-11-09     1035
    ## 11361    NA 2012-11-09     1040
    ## 11362    NA 2012-11-09     1045
    ## 11363    NA 2012-11-09     1050
    ## 11364    NA 2012-11-09     1055
    ## 11365    NA 2012-11-09     1100
    ## 11366    NA 2012-11-09     1105
    ## 11367    NA 2012-11-09     1110
    ## 11368    NA 2012-11-09     1115
    ## 11369    NA 2012-11-09     1120
    ## 11370    NA 2012-11-09     1125
    ## 11371    NA 2012-11-09     1130
    ## 11372    NA 2012-11-09     1135
    ## 11373    NA 2012-11-09     1140
    ## 11374    NA 2012-11-09     1145
    ## 11375    NA 2012-11-09     1150
    ## 11376    NA 2012-11-09     1155
    ## 11377    NA 2012-11-09     1200
    ## 11378    NA 2012-11-09     1205
    ## 11379    NA 2012-11-09     1210
    ## 11380    NA 2012-11-09     1215
    ## 11381    NA 2012-11-09     1220
    ## 11382    NA 2012-11-09     1225
    ## 11383    NA 2012-11-09     1230
    ## 11384    NA 2012-11-09     1235
    ## 11385    NA 2012-11-09     1240
    ## 11386    NA 2012-11-09     1245
    ## 11387    NA 2012-11-09     1250
    ## 11388    NA 2012-11-09     1255
    ## 11389    NA 2012-11-09     1300
    ## 11390    NA 2012-11-09     1305
    ## 11391    NA 2012-11-09     1310
    ## 11392    NA 2012-11-09     1315
    ## 11393    NA 2012-11-09     1320
    ## 11394    NA 2012-11-09     1325
    ## 11395    NA 2012-11-09     1330
    ## 11396    NA 2012-11-09     1335
    ## 11397    NA 2012-11-09     1340
    ## 11398    NA 2012-11-09     1345
    ## 11399    NA 2012-11-09     1350
    ## 11400    NA 2012-11-09     1355
    ## 11401    NA 2012-11-09     1400
    ## 11402    NA 2012-11-09     1405
    ## 11403    NA 2012-11-09     1410
    ## 11404    NA 2012-11-09     1415
    ## 11405    NA 2012-11-09     1420
    ## 11406    NA 2012-11-09     1425
    ## 11407    NA 2012-11-09     1430
    ## 11408    NA 2012-11-09     1435
    ## 11409    NA 2012-11-09     1440
    ## 11410    NA 2012-11-09     1445
    ## 11411    NA 2012-11-09     1450
    ## 11412    NA 2012-11-09     1455
    ## 11413    NA 2012-11-09     1500
    ## 11414    NA 2012-11-09     1505
    ## 11415    NA 2012-11-09     1510
    ## 11416    NA 2012-11-09     1515
    ## 11417    NA 2012-11-09     1520
    ## 11418    NA 2012-11-09     1525
    ## 11419    NA 2012-11-09     1530
    ## 11420    NA 2012-11-09     1535
    ## 11421    NA 2012-11-09     1540
    ## 11422    NA 2012-11-09     1545
    ## 11423    NA 2012-11-09     1550
    ## 11424    NA 2012-11-09     1555
    ## 11425    NA 2012-11-09     1600
    ## 11426    NA 2012-11-09     1605
    ## 11427    NA 2012-11-09     1610
    ## 11428    NA 2012-11-09     1615
    ## 11429    NA 2012-11-09     1620
    ## 11430    NA 2012-11-09     1625
    ## 11431    NA 2012-11-09     1630
    ## 11432    NA 2012-11-09     1635
    ## 11433    NA 2012-11-09     1640
    ## 11434    NA 2012-11-09     1645
    ## 11435    NA 2012-11-09     1650
    ## 11436    NA 2012-11-09     1655
    ## 11437    NA 2012-11-09     1700
    ## 11438    NA 2012-11-09     1705
    ## 11439    NA 2012-11-09     1710
    ## 11440    NA 2012-11-09     1715
    ## 11441    NA 2012-11-09     1720
    ## 11442    NA 2012-11-09     1725
    ## 11443    NA 2012-11-09     1730
    ## 11444    NA 2012-11-09     1735
    ## 11445    NA 2012-11-09     1740
    ## 11446    NA 2012-11-09     1745
    ## 11447    NA 2012-11-09     1750
    ## 11448    NA 2012-11-09     1755
    ## 11449    NA 2012-11-09     1800
    ## 11450    NA 2012-11-09     1805
    ## 11451    NA 2012-11-09     1810
    ## 11452    NA 2012-11-09     1815
    ## 11453    NA 2012-11-09     1820
    ## 11454    NA 2012-11-09     1825
    ## 11455    NA 2012-11-09     1830
    ## 11456    NA 2012-11-09     1835
    ## 11457    NA 2012-11-09     1840
    ## 11458    NA 2012-11-09     1845
    ## 11459    NA 2012-11-09     1850
    ## 11460    NA 2012-11-09     1855
    ## 11461    NA 2012-11-09     1900
    ## 11462    NA 2012-11-09     1905
    ## 11463    NA 2012-11-09     1910
    ## 11464    NA 2012-11-09     1915
    ## 11465    NA 2012-11-09     1920
    ## 11466    NA 2012-11-09     1925
    ## 11467    NA 2012-11-09     1930
    ## 11468    NA 2012-11-09     1935
    ## 11469    NA 2012-11-09     1940
    ## 11470    NA 2012-11-09     1945
    ## 11471    NA 2012-11-09     1950
    ## 11472    NA 2012-11-09     1955
    ## 11473    NA 2012-11-09     2000
    ## 11474    NA 2012-11-09     2005
    ## 11475    NA 2012-11-09     2010
    ## 11476    NA 2012-11-09     2015
    ## 11477    NA 2012-11-09     2020
    ## 11478    NA 2012-11-09     2025
    ## 11479    NA 2012-11-09     2030
    ## 11480    NA 2012-11-09     2035
    ## 11481    NA 2012-11-09     2040
    ## 11482    NA 2012-11-09     2045
    ## 11483    NA 2012-11-09     2050
    ## 11484    NA 2012-11-09     2055
    ## 11485    NA 2012-11-09     2100
    ## 11486    NA 2012-11-09     2105
    ## 11487    NA 2012-11-09     2110
    ## 11488    NA 2012-11-09     2115
    ## 11489    NA 2012-11-09     2120
    ## 11490    NA 2012-11-09     2125
    ## 11491    NA 2012-11-09     2130
    ## 11492    NA 2012-11-09     2135
    ## 11493    NA 2012-11-09     2140
    ## 11494    NA 2012-11-09     2145
    ## 11495    NA 2012-11-09     2150
    ## 11496    NA 2012-11-09     2155
    ## 11497    NA 2012-11-09     2200
    ## 11498    NA 2012-11-09     2205
    ## 11499    NA 2012-11-09     2210
    ## 11500    NA 2012-11-09     2215
    ## 11501    NA 2012-11-09     2220
    ## 11502    NA 2012-11-09     2225
    ## 11503    NA 2012-11-09     2230
    ## 11504    NA 2012-11-09     2235
    ## 11505    NA 2012-11-09     2240
    ## 11506    NA 2012-11-09     2245
    ## 11507    NA 2012-11-09     2250
    ## 11508    NA 2012-11-09     2255
    ## 11509    NA 2012-11-09     2300
    ## 11510    NA 2012-11-09     2305
    ## 11511    NA 2012-11-09     2310
    ## 11512    NA 2012-11-09     2315
    ## 11513    NA 2012-11-09     2320
    ## 11514    NA 2012-11-09     2325
    ## 11515    NA 2012-11-09     2330
    ## 11516    NA 2012-11-09     2335
    ## 11517    NA 2012-11-09     2340
    ## 11518    NA 2012-11-09     2345
    ## 11519    NA 2012-11-09     2350
    ## 11520    NA 2012-11-09     2355
    ## 11521    NA 2012-11-10        0
    ## 11522    NA 2012-11-10        5
    ## 11523    NA 2012-11-10       10
    ## 11524    NA 2012-11-10       15
    ## 11525    NA 2012-11-10       20
    ## 11526    NA 2012-11-10       25
    ## 11527    NA 2012-11-10       30
    ## 11528    NA 2012-11-10       35
    ## 11529    NA 2012-11-10       40
    ## 11530    NA 2012-11-10       45
    ## 11531    NA 2012-11-10       50
    ## 11532    NA 2012-11-10       55
    ## 11533    NA 2012-11-10      100
    ## 11534    NA 2012-11-10      105
    ## 11535    NA 2012-11-10      110
    ## 11536    NA 2012-11-10      115
    ## 11537    NA 2012-11-10      120
    ## 11538    NA 2012-11-10      125
    ## 11539    NA 2012-11-10      130
    ## 11540    NA 2012-11-10      135
    ## 11541    NA 2012-11-10      140
    ## 11542    NA 2012-11-10      145
    ## 11543    NA 2012-11-10      150
    ## 11544    NA 2012-11-10      155
    ## 11545    NA 2012-11-10      200
    ## 11546    NA 2012-11-10      205
    ## 11547    NA 2012-11-10      210
    ## 11548    NA 2012-11-10      215
    ## 11549    NA 2012-11-10      220
    ## 11550    NA 2012-11-10      225
    ## 11551    NA 2012-11-10      230
    ## 11552    NA 2012-11-10      235
    ## 11553    NA 2012-11-10      240
    ## 11554    NA 2012-11-10      245
    ## 11555    NA 2012-11-10      250
    ## 11556    NA 2012-11-10      255
    ## 11557    NA 2012-11-10      300
    ## 11558    NA 2012-11-10      305
    ## 11559    NA 2012-11-10      310
    ## 11560    NA 2012-11-10      315
    ## 11561    NA 2012-11-10      320
    ## 11562    NA 2012-11-10      325
    ## 11563    NA 2012-11-10      330
    ## 11564    NA 2012-11-10      335
    ## 11565    NA 2012-11-10      340
    ## 11566    NA 2012-11-10      345
    ## 11567    NA 2012-11-10      350
    ## 11568    NA 2012-11-10      355
    ## 11569    NA 2012-11-10      400
    ## 11570    NA 2012-11-10      405
    ## 11571    NA 2012-11-10      410
    ## 11572    NA 2012-11-10      415
    ## 11573    NA 2012-11-10      420
    ## 11574    NA 2012-11-10      425
    ## 11575    NA 2012-11-10      430
    ## 11576    NA 2012-11-10      435
    ## 11577    NA 2012-11-10      440
    ## 11578    NA 2012-11-10      445
    ## 11579    NA 2012-11-10      450
    ## 11580    NA 2012-11-10      455
    ## 11581    NA 2012-11-10      500
    ## 11582    NA 2012-11-10      505
    ## 11583    NA 2012-11-10      510
    ## 11584    NA 2012-11-10      515
    ## 11585    NA 2012-11-10      520
    ## 11586    NA 2012-11-10      525
    ## 11587    NA 2012-11-10      530
    ## 11588    NA 2012-11-10      535
    ## 11589    NA 2012-11-10      540
    ## 11590    NA 2012-11-10      545
    ## 11591    NA 2012-11-10      550
    ## 11592    NA 2012-11-10      555
    ## 11593    NA 2012-11-10      600
    ## 11594    NA 2012-11-10      605
    ## 11595    NA 2012-11-10      610
    ## 11596    NA 2012-11-10      615
    ## 11597    NA 2012-11-10      620
    ## 11598    NA 2012-11-10      625
    ## 11599    NA 2012-11-10      630
    ## 11600    NA 2012-11-10      635
    ## 11601    NA 2012-11-10      640
    ## 11602    NA 2012-11-10      645
    ## 11603    NA 2012-11-10      650
    ## 11604    NA 2012-11-10      655
    ## 11605    NA 2012-11-10      700
    ## 11606    NA 2012-11-10      705
    ## 11607    NA 2012-11-10      710
    ## 11608    NA 2012-11-10      715
    ## 11609    NA 2012-11-10      720
    ## 11610    NA 2012-11-10      725
    ## 11611    NA 2012-11-10      730
    ## 11612    NA 2012-11-10      735
    ## 11613    NA 2012-11-10      740
    ## 11614    NA 2012-11-10      745
    ## 11615    NA 2012-11-10      750
    ## 11616    NA 2012-11-10      755
    ## 11617    NA 2012-11-10      800
    ## 11618    NA 2012-11-10      805
    ## 11619    NA 2012-11-10      810
    ## 11620    NA 2012-11-10      815
    ## 11621    NA 2012-11-10      820
    ## 11622    NA 2012-11-10      825
    ## 11623    NA 2012-11-10      830
    ## 11624    NA 2012-11-10      835
    ## 11625    NA 2012-11-10      840
    ## 11626    NA 2012-11-10      845
    ## 11627    NA 2012-11-10      850
    ## 11628    NA 2012-11-10      855
    ## 11629    NA 2012-11-10      900
    ## 11630    NA 2012-11-10      905
    ## 11631    NA 2012-11-10      910
    ## 11632    NA 2012-11-10      915
    ## 11633    NA 2012-11-10      920
    ## 11634    NA 2012-11-10      925
    ## 11635    NA 2012-11-10      930
    ## 11636    NA 2012-11-10      935
    ## 11637    NA 2012-11-10      940
    ## 11638    NA 2012-11-10      945
    ## 11639    NA 2012-11-10      950
    ## 11640    NA 2012-11-10      955
    ## 11641    NA 2012-11-10     1000
    ## 11642    NA 2012-11-10     1005
    ## 11643    NA 2012-11-10     1010
    ## 11644    NA 2012-11-10     1015
    ## 11645    NA 2012-11-10     1020
    ## 11646    NA 2012-11-10     1025
    ## 11647    NA 2012-11-10     1030
    ## 11648    NA 2012-11-10     1035
    ## 11649    NA 2012-11-10     1040
    ## 11650    NA 2012-11-10     1045
    ## 11651    NA 2012-11-10     1050
    ## 11652    NA 2012-11-10     1055
    ## 11653    NA 2012-11-10     1100
    ## 11654    NA 2012-11-10     1105
    ## 11655    NA 2012-11-10     1110
    ## 11656    NA 2012-11-10     1115
    ## 11657    NA 2012-11-10     1120
    ## 11658    NA 2012-11-10     1125
    ## 11659    NA 2012-11-10     1130
    ## 11660    NA 2012-11-10     1135
    ## 11661    NA 2012-11-10     1140
    ## 11662    NA 2012-11-10     1145
    ## 11663    NA 2012-11-10     1150
    ## 11664    NA 2012-11-10     1155
    ## 11665    NA 2012-11-10     1200
    ## 11666    NA 2012-11-10     1205
    ## 11667    NA 2012-11-10     1210
    ## 11668    NA 2012-11-10     1215
    ## 11669    NA 2012-11-10     1220
    ## 11670    NA 2012-11-10     1225
    ## 11671    NA 2012-11-10     1230
    ## 11672    NA 2012-11-10     1235
    ## 11673    NA 2012-11-10     1240
    ## 11674    NA 2012-11-10     1245
    ## 11675    NA 2012-11-10     1250
    ## 11676    NA 2012-11-10     1255
    ## 11677    NA 2012-11-10     1300
    ## 11678    NA 2012-11-10     1305
    ## 11679    NA 2012-11-10     1310
    ## 11680    NA 2012-11-10     1315
    ## 11681    NA 2012-11-10     1320
    ## 11682    NA 2012-11-10     1325
    ## 11683    NA 2012-11-10     1330
    ## 11684    NA 2012-11-10     1335
    ## 11685    NA 2012-11-10     1340
    ## 11686    NA 2012-11-10     1345
    ## 11687    NA 2012-11-10     1350
    ## 11688    NA 2012-11-10     1355
    ## 11689    NA 2012-11-10     1400
    ## 11690    NA 2012-11-10     1405
    ## 11691    NA 2012-11-10     1410
    ## 11692    NA 2012-11-10     1415
    ## 11693    NA 2012-11-10     1420
    ## 11694    NA 2012-11-10     1425
    ## 11695    NA 2012-11-10     1430
    ## 11696    NA 2012-11-10     1435
    ## 11697    NA 2012-11-10     1440
    ## 11698    NA 2012-11-10     1445
    ## 11699    NA 2012-11-10     1450
    ## 11700    NA 2012-11-10     1455
    ## 11701    NA 2012-11-10     1500
    ## 11702    NA 2012-11-10     1505
    ## 11703    NA 2012-11-10     1510
    ## 11704    NA 2012-11-10     1515
    ## 11705    NA 2012-11-10     1520
    ## 11706    NA 2012-11-10     1525
    ## 11707    NA 2012-11-10     1530
    ## 11708    NA 2012-11-10     1535
    ## 11709    NA 2012-11-10     1540
    ## 11710    NA 2012-11-10     1545
    ## 11711    NA 2012-11-10     1550
    ## 11712    NA 2012-11-10     1555
    ## 11713    NA 2012-11-10     1600
    ## 11714    NA 2012-11-10     1605
    ## 11715    NA 2012-11-10     1610
    ## 11716    NA 2012-11-10     1615
    ## 11717    NA 2012-11-10     1620
    ## 11718    NA 2012-11-10     1625
    ## 11719    NA 2012-11-10     1630
    ## 11720    NA 2012-11-10     1635
    ## 11721    NA 2012-11-10     1640
    ## 11722    NA 2012-11-10     1645
    ## 11723    NA 2012-11-10     1650
    ## 11724    NA 2012-11-10     1655
    ## 11725    NA 2012-11-10     1700
    ## 11726    NA 2012-11-10     1705
    ## 11727    NA 2012-11-10     1710
    ## 11728    NA 2012-11-10     1715
    ## 11729    NA 2012-11-10     1720
    ## 11730    NA 2012-11-10     1725
    ## 11731    NA 2012-11-10     1730
    ## 11732    NA 2012-11-10     1735
    ## 11733    NA 2012-11-10     1740
    ## 11734    NA 2012-11-10     1745
    ## 11735    NA 2012-11-10     1750
    ## 11736    NA 2012-11-10     1755
    ## 11737    NA 2012-11-10     1800
    ## 11738    NA 2012-11-10     1805
    ## 11739    NA 2012-11-10     1810
    ## 11740    NA 2012-11-10     1815
    ## 11741    NA 2012-11-10     1820
    ## 11742    NA 2012-11-10     1825
    ## 11743    NA 2012-11-10     1830
    ## 11744    NA 2012-11-10     1835
    ## 11745    NA 2012-11-10     1840
    ## 11746    NA 2012-11-10     1845
    ## 11747    NA 2012-11-10     1850
    ## 11748    NA 2012-11-10     1855
    ## 11749    NA 2012-11-10     1900
    ## 11750    NA 2012-11-10     1905
    ## 11751    NA 2012-11-10     1910
    ## 11752    NA 2012-11-10     1915
    ## 11753    NA 2012-11-10     1920
    ## 11754    NA 2012-11-10     1925
    ## 11755    NA 2012-11-10     1930
    ## 11756    NA 2012-11-10     1935
    ## 11757    NA 2012-11-10     1940
    ## 11758    NA 2012-11-10     1945
    ## 11759    NA 2012-11-10     1950
    ## 11760    NA 2012-11-10     1955
    ## 11761    NA 2012-11-10     2000
    ## 11762    NA 2012-11-10     2005
    ## 11763    NA 2012-11-10     2010
    ## 11764    NA 2012-11-10     2015
    ## 11765    NA 2012-11-10     2020
    ## 11766    NA 2012-11-10     2025
    ## 11767    NA 2012-11-10     2030
    ## 11768    NA 2012-11-10     2035
    ## 11769    NA 2012-11-10     2040
    ## 11770    NA 2012-11-10     2045
    ## 11771    NA 2012-11-10     2050
    ## 11772    NA 2012-11-10     2055
    ## 11773    NA 2012-11-10     2100
    ## 11774    NA 2012-11-10     2105
    ## 11775    NA 2012-11-10     2110
    ## 11776    NA 2012-11-10     2115
    ## 11777    NA 2012-11-10     2120
    ## 11778    NA 2012-11-10     2125
    ## 11779    NA 2012-11-10     2130
    ## 11780    NA 2012-11-10     2135
    ## 11781    NA 2012-11-10     2140
    ## 11782    NA 2012-11-10     2145
    ## 11783    NA 2012-11-10     2150
    ## 11784    NA 2012-11-10     2155
    ## 11785    NA 2012-11-10     2200
    ## 11786    NA 2012-11-10     2205
    ## 11787    NA 2012-11-10     2210
    ## 11788    NA 2012-11-10     2215
    ## 11789    NA 2012-11-10     2220
    ## 11790    NA 2012-11-10     2225
    ## 11791    NA 2012-11-10     2230
    ## 11792    NA 2012-11-10     2235
    ## 11793    NA 2012-11-10     2240
    ## 11794    NA 2012-11-10     2245
    ## 11795    NA 2012-11-10     2250
    ## 11796    NA 2012-11-10     2255
    ## 11797    NA 2012-11-10     2300
    ## 11798    NA 2012-11-10     2305
    ## 11799    NA 2012-11-10     2310
    ## 11800    NA 2012-11-10     2315
    ## 11801    NA 2012-11-10     2320
    ## 11802    NA 2012-11-10     2325
    ## 11803    NA 2012-11-10     2330
    ## 11804    NA 2012-11-10     2335
    ## 11805    NA 2012-11-10     2340
    ## 11806    NA 2012-11-10     2345
    ## 11807    NA 2012-11-10     2350
    ## 11808    NA 2012-11-10     2355
    ## 12673    NA 2012-11-14        0
    ## 12674    NA 2012-11-14        5
    ## 12675    NA 2012-11-14       10
    ## 12676    NA 2012-11-14       15
    ## 12677    NA 2012-11-14       20
    ## 12678    NA 2012-11-14       25
    ## 12679    NA 2012-11-14       30
    ## 12680    NA 2012-11-14       35
    ## 12681    NA 2012-11-14       40
    ## 12682    NA 2012-11-14       45
    ## 12683    NA 2012-11-14       50
    ## 12684    NA 2012-11-14       55
    ## 12685    NA 2012-11-14      100
    ## 12686    NA 2012-11-14      105
    ## 12687    NA 2012-11-14      110
    ## 12688    NA 2012-11-14      115
    ## 12689    NA 2012-11-14      120
    ## 12690    NA 2012-11-14      125
    ## 12691    NA 2012-11-14      130
    ## 12692    NA 2012-11-14      135
    ## 12693    NA 2012-11-14      140
    ## 12694    NA 2012-11-14      145
    ## 12695    NA 2012-11-14      150
    ## 12696    NA 2012-11-14      155
    ## 12697    NA 2012-11-14      200
    ## 12698    NA 2012-11-14      205
    ## 12699    NA 2012-11-14      210
    ## 12700    NA 2012-11-14      215
    ## 12701    NA 2012-11-14      220
    ## 12702    NA 2012-11-14      225
    ## 12703    NA 2012-11-14      230
    ## 12704    NA 2012-11-14      235
    ## 12705    NA 2012-11-14      240
    ## 12706    NA 2012-11-14      245
    ## 12707    NA 2012-11-14      250
    ## 12708    NA 2012-11-14      255
    ## 12709    NA 2012-11-14      300
    ## 12710    NA 2012-11-14      305
    ## 12711    NA 2012-11-14      310
    ## 12712    NA 2012-11-14      315
    ## 12713    NA 2012-11-14      320
    ## 12714    NA 2012-11-14      325
    ## 12715    NA 2012-11-14      330
    ## 12716    NA 2012-11-14      335
    ## 12717    NA 2012-11-14      340
    ## 12718    NA 2012-11-14      345
    ## 12719    NA 2012-11-14      350
    ## 12720    NA 2012-11-14      355
    ## 12721    NA 2012-11-14      400
    ## 12722    NA 2012-11-14      405
    ## 12723    NA 2012-11-14      410
    ## 12724    NA 2012-11-14      415
    ## 12725    NA 2012-11-14      420
    ## 12726    NA 2012-11-14      425
    ## 12727    NA 2012-11-14      430
    ## 12728    NA 2012-11-14      435
    ## 12729    NA 2012-11-14      440
    ## 12730    NA 2012-11-14      445
    ## 12731    NA 2012-11-14      450
    ## 12732    NA 2012-11-14      455
    ## 12733    NA 2012-11-14      500
    ## 12734    NA 2012-11-14      505
    ## 12735    NA 2012-11-14      510
    ## 12736    NA 2012-11-14      515
    ## 12737    NA 2012-11-14      520
    ## 12738    NA 2012-11-14      525
    ## 12739    NA 2012-11-14      530
    ## 12740    NA 2012-11-14      535
    ## 12741    NA 2012-11-14      540
    ## 12742    NA 2012-11-14      545
    ## 12743    NA 2012-11-14      550
    ## 12744    NA 2012-11-14      555
    ## 12745    NA 2012-11-14      600
    ## 12746    NA 2012-11-14      605
    ## 12747    NA 2012-11-14      610
    ## 12748    NA 2012-11-14      615
    ## 12749    NA 2012-11-14      620
    ## 12750    NA 2012-11-14      625
    ## 12751    NA 2012-11-14      630
    ## 12752    NA 2012-11-14      635
    ## 12753    NA 2012-11-14      640
    ## 12754    NA 2012-11-14      645
    ## 12755    NA 2012-11-14      650
    ## 12756    NA 2012-11-14      655
    ## 12757    NA 2012-11-14      700
    ## 12758    NA 2012-11-14      705
    ## 12759    NA 2012-11-14      710
    ## 12760    NA 2012-11-14      715
    ## 12761    NA 2012-11-14      720
    ## 12762    NA 2012-11-14      725
    ## 12763    NA 2012-11-14      730
    ## 12764    NA 2012-11-14      735
    ## 12765    NA 2012-11-14      740
    ## 12766    NA 2012-11-14      745
    ## 12767    NA 2012-11-14      750
    ## 12768    NA 2012-11-14      755
    ## 12769    NA 2012-11-14      800
    ## 12770    NA 2012-11-14      805
    ## 12771    NA 2012-11-14      810
    ## 12772    NA 2012-11-14      815
    ## 12773    NA 2012-11-14      820
    ## 12774    NA 2012-11-14      825
    ## 12775    NA 2012-11-14      830
    ## 12776    NA 2012-11-14      835
    ## 12777    NA 2012-11-14      840
    ## 12778    NA 2012-11-14      845
    ## 12779    NA 2012-11-14      850
    ## 12780    NA 2012-11-14      855
    ## 12781    NA 2012-11-14      900
    ## 12782    NA 2012-11-14      905
    ## 12783    NA 2012-11-14      910
    ## 12784    NA 2012-11-14      915
    ## 12785    NA 2012-11-14      920
    ## 12786    NA 2012-11-14      925
    ## 12787    NA 2012-11-14      930
    ## 12788    NA 2012-11-14      935
    ## 12789    NA 2012-11-14      940
    ## 12790    NA 2012-11-14      945
    ## 12791    NA 2012-11-14      950
    ## 12792    NA 2012-11-14      955
    ## 12793    NA 2012-11-14     1000
    ## 12794    NA 2012-11-14     1005
    ## 12795    NA 2012-11-14     1010
    ## 12796    NA 2012-11-14     1015
    ## 12797    NA 2012-11-14     1020
    ## 12798    NA 2012-11-14     1025
    ## 12799    NA 2012-11-14     1030
    ## 12800    NA 2012-11-14     1035
    ## 12801    NA 2012-11-14     1040
    ## 12802    NA 2012-11-14     1045
    ## 12803    NA 2012-11-14     1050
    ## 12804    NA 2012-11-14     1055
    ## 12805    NA 2012-11-14     1100
    ## 12806    NA 2012-11-14     1105
    ## 12807    NA 2012-11-14     1110
    ## 12808    NA 2012-11-14     1115
    ## 12809    NA 2012-11-14     1120
    ## 12810    NA 2012-11-14     1125
    ## 12811    NA 2012-11-14     1130
    ## 12812    NA 2012-11-14     1135
    ## 12813    NA 2012-11-14     1140
    ## 12814    NA 2012-11-14     1145
    ## 12815    NA 2012-11-14     1150
    ## 12816    NA 2012-11-14     1155
    ## 12817    NA 2012-11-14     1200
    ## 12818    NA 2012-11-14     1205
    ## 12819    NA 2012-11-14     1210
    ## 12820    NA 2012-11-14     1215
    ## 12821    NA 2012-11-14     1220
    ## 12822    NA 2012-11-14     1225
    ## 12823    NA 2012-11-14     1230
    ## 12824    NA 2012-11-14     1235
    ## 12825    NA 2012-11-14     1240
    ## 12826    NA 2012-11-14     1245
    ## 12827    NA 2012-11-14     1250
    ## 12828    NA 2012-11-14     1255
    ## 12829    NA 2012-11-14     1300
    ## 12830    NA 2012-11-14     1305
    ## 12831    NA 2012-11-14     1310
    ## 12832    NA 2012-11-14     1315
    ## 12833    NA 2012-11-14     1320
    ## 12834    NA 2012-11-14     1325
    ## 12835    NA 2012-11-14     1330
    ## 12836    NA 2012-11-14     1335
    ## 12837    NA 2012-11-14     1340
    ## 12838    NA 2012-11-14     1345
    ## 12839    NA 2012-11-14     1350
    ## 12840    NA 2012-11-14     1355
    ## 12841    NA 2012-11-14     1400
    ## 12842    NA 2012-11-14     1405
    ## 12843    NA 2012-11-14     1410
    ## 12844    NA 2012-11-14     1415
    ## 12845    NA 2012-11-14     1420
    ## 12846    NA 2012-11-14     1425
    ## 12847    NA 2012-11-14     1430
    ## 12848    NA 2012-11-14     1435
    ## 12849    NA 2012-11-14     1440
    ## 12850    NA 2012-11-14     1445
    ## 12851    NA 2012-11-14     1450
    ## 12852    NA 2012-11-14     1455
    ## 12853    NA 2012-11-14     1500
    ## 12854    NA 2012-11-14     1505
    ## 12855    NA 2012-11-14     1510
    ## 12856    NA 2012-11-14     1515
    ## 12857    NA 2012-11-14     1520
    ## 12858    NA 2012-11-14     1525
    ## 12859    NA 2012-11-14     1530
    ## 12860    NA 2012-11-14     1535
    ## 12861    NA 2012-11-14     1540
    ## 12862    NA 2012-11-14     1545
    ## 12863    NA 2012-11-14     1550
    ## 12864    NA 2012-11-14     1555
    ## 12865    NA 2012-11-14     1600
    ## 12866    NA 2012-11-14     1605
    ## 12867    NA 2012-11-14     1610
    ## 12868    NA 2012-11-14     1615
    ## 12869    NA 2012-11-14     1620
    ## 12870    NA 2012-11-14     1625
    ## 12871    NA 2012-11-14     1630
    ## 12872    NA 2012-11-14     1635
    ## 12873    NA 2012-11-14     1640
    ## 12874    NA 2012-11-14     1645
    ## 12875    NA 2012-11-14     1650
    ## 12876    NA 2012-11-14     1655
    ## 12877    NA 2012-11-14     1700
    ## 12878    NA 2012-11-14     1705
    ## 12879    NA 2012-11-14     1710
    ## 12880    NA 2012-11-14     1715
    ## 12881    NA 2012-11-14     1720
    ## 12882    NA 2012-11-14     1725
    ## 12883    NA 2012-11-14     1730
    ## 12884    NA 2012-11-14     1735
    ## 12885    NA 2012-11-14     1740
    ## 12886    NA 2012-11-14     1745
    ## 12887    NA 2012-11-14     1750
    ## 12888    NA 2012-11-14     1755
    ## 12889    NA 2012-11-14     1800
    ## 12890    NA 2012-11-14     1805
    ## 12891    NA 2012-11-14     1810
    ## 12892    NA 2012-11-14     1815
    ## 12893    NA 2012-11-14     1820
    ## 12894    NA 2012-11-14     1825
    ## 12895    NA 2012-11-14     1830
    ## 12896    NA 2012-11-14     1835
    ## 12897    NA 2012-11-14     1840
    ## 12898    NA 2012-11-14     1845
    ## 12899    NA 2012-11-14     1850
    ## 12900    NA 2012-11-14     1855
    ## 12901    NA 2012-11-14     1900
    ## 12902    NA 2012-11-14     1905
    ## 12903    NA 2012-11-14     1910
    ## 12904    NA 2012-11-14     1915
    ## 12905    NA 2012-11-14     1920
    ## 12906    NA 2012-11-14     1925
    ## 12907    NA 2012-11-14     1930
    ## 12908    NA 2012-11-14     1935
    ## 12909    NA 2012-11-14     1940
    ## 12910    NA 2012-11-14     1945
    ## 12911    NA 2012-11-14     1950
    ## 12912    NA 2012-11-14     1955
    ## 12913    NA 2012-11-14     2000
    ## 12914    NA 2012-11-14     2005
    ## 12915    NA 2012-11-14     2010
    ## 12916    NA 2012-11-14     2015
    ## 12917    NA 2012-11-14     2020
    ## 12918    NA 2012-11-14     2025
    ## 12919    NA 2012-11-14     2030
    ## 12920    NA 2012-11-14     2035
    ## 12921    NA 2012-11-14     2040
    ## 12922    NA 2012-11-14     2045
    ## 12923    NA 2012-11-14     2050
    ## 12924    NA 2012-11-14     2055
    ## 12925    NA 2012-11-14     2100
    ## 12926    NA 2012-11-14     2105
    ## 12927    NA 2012-11-14     2110
    ## 12928    NA 2012-11-14     2115
    ## 12929    NA 2012-11-14     2120
    ## 12930    NA 2012-11-14     2125
    ## 12931    NA 2012-11-14     2130
    ## 12932    NA 2012-11-14     2135
    ## 12933    NA 2012-11-14     2140
    ## 12934    NA 2012-11-14     2145
    ## 12935    NA 2012-11-14     2150
    ## 12936    NA 2012-11-14     2155
    ## 12937    NA 2012-11-14     2200
    ## 12938    NA 2012-11-14     2205
    ## 12939    NA 2012-11-14     2210
    ## 12940    NA 2012-11-14     2215
    ## 12941    NA 2012-11-14     2220
    ## 12942    NA 2012-11-14     2225
    ## 12943    NA 2012-11-14     2230
    ## 12944    NA 2012-11-14     2235
    ## 12945    NA 2012-11-14     2240
    ## 12946    NA 2012-11-14     2245
    ## 12947    NA 2012-11-14     2250
    ## 12948    NA 2012-11-14     2255
    ## 12949    NA 2012-11-14     2300
    ## 12950    NA 2012-11-14     2305
    ## 12951    NA 2012-11-14     2310
    ## 12952    NA 2012-11-14     2315
    ## 12953    NA 2012-11-14     2320
    ## 12954    NA 2012-11-14     2325
    ## 12955    NA 2012-11-14     2330
    ## 12956    NA 2012-11-14     2335
    ## 12957    NA 2012-11-14     2340
    ## 12958    NA 2012-11-14     2345
    ## 12959    NA 2012-11-14     2350
    ## 12960    NA 2012-11-14     2355
    ## 17281    NA 2012-11-30        0
    ## 17282    NA 2012-11-30        5
    ## 17283    NA 2012-11-30       10
    ## 17284    NA 2012-11-30       15
    ## 17285    NA 2012-11-30       20
    ## 17286    NA 2012-11-30       25
    ## 17287    NA 2012-11-30       30
    ## 17288    NA 2012-11-30       35
    ## 17289    NA 2012-11-30       40
    ## 17290    NA 2012-11-30       45
    ## 17291    NA 2012-11-30       50
    ## 17292    NA 2012-11-30       55
    ## 17293    NA 2012-11-30      100
    ## 17294    NA 2012-11-30      105
    ## 17295    NA 2012-11-30      110
    ## 17296    NA 2012-11-30      115
    ## 17297    NA 2012-11-30      120
    ## 17298    NA 2012-11-30      125
    ## 17299    NA 2012-11-30      130
    ## 17300    NA 2012-11-30      135
    ## 17301    NA 2012-11-30      140
    ## 17302    NA 2012-11-30      145
    ## 17303    NA 2012-11-30      150
    ## 17304    NA 2012-11-30      155
    ## 17305    NA 2012-11-30      200
    ## 17306    NA 2012-11-30      205
    ## 17307    NA 2012-11-30      210
    ## 17308    NA 2012-11-30      215
    ## 17309    NA 2012-11-30      220
    ## 17310    NA 2012-11-30      225
    ## 17311    NA 2012-11-30      230
    ## 17312    NA 2012-11-30      235
    ## 17313    NA 2012-11-30      240
    ## 17314    NA 2012-11-30      245
    ## 17315    NA 2012-11-30      250
    ## 17316    NA 2012-11-30      255
    ## 17317    NA 2012-11-30      300
    ## 17318    NA 2012-11-30      305
    ## 17319    NA 2012-11-30      310
    ## 17320    NA 2012-11-30      315
    ## 17321    NA 2012-11-30      320
    ## 17322    NA 2012-11-30      325
    ## 17323    NA 2012-11-30      330
    ## 17324    NA 2012-11-30      335
    ## 17325    NA 2012-11-30      340
    ## 17326    NA 2012-11-30      345
    ## 17327    NA 2012-11-30      350
    ## 17328    NA 2012-11-30      355
    ## 17329    NA 2012-11-30      400
    ## 17330    NA 2012-11-30      405
    ## 17331    NA 2012-11-30      410
    ## 17332    NA 2012-11-30      415
    ## 17333    NA 2012-11-30      420
    ## 17334    NA 2012-11-30      425
    ## 17335    NA 2012-11-30      430
    ## 17336    NA 2012-11-30      435
    ## 17337    NA 2012-11-30      440
    ## 17338    NA 2012-11-30      445
    ## 17339    NA 2012-11-30      450
    ## 17340    NA 2012-11-30      455
    ## 17341    NA 2012-11-30      500
    ## 17342    NA 2012-11-30      505
    ## 17343    NA 2012-11-30      510
    ## 17344    NA 2012-11-30      515
    ## 17345    NA 2012-11-30      520
    ## 17346    NA 2012-11-30      525
    ## 17347    NA 2012-11-30      530
    ## 17348    NA 2012-11-30      535
    ## 17349    NA 2012-11-30      540
    ## 17350    NA 2012-11-30      545
    ## 17351    NA 2012-11-30      550
    ## 17352    NA 2012-11-30      555
    ## 17353    NA 2012-11-30      600
    ## 17354    NA 2012-11-30      605
    ## 17355    NA 2012-11-30      610
    ## 17356    NA 2012-11-30      615
    ## 17357    NA 2012-11-30      620
    ## 17358    NA 2012-11-30      625
    ## 17359    NA 2012-11-30      630
    ## 17360    NA 2012-11-30      635
    ## 17361    NA 2012-11-30      640
    ## 17362    NA 2012-11-30      645
    ## 17363    NA 2012-11-30      650
    ## 17364    NA 2012-11-30      655
    ## 17365    NA 2012-11-30      700
    ## 17366    NA 2012-11-30      705
    ## 17367    NA 2012-11-30      710
    ## 17368    NA 2012-11-30      715
    ## 17369    NA 2012-11-30      720
    ## 17370    NA 2012-11-30      725
    ## 17371    NA 2012-11-30      730
    ## 17372    NA 2012-11-30      735
    ## 17373    NA 2012-11-30      740
    ## 17374    NA 2012-11-30      745
    ## 17375    NA 2012-11-30      750
    ## 17376    NA 2012-11-30      755
    ## 17377    NA 2012-11-30      800
    ## 17378    NA 2012-11-30      805
    ## 17379    NA 2012-11-30      810
    ## 17380    NA 2012-11-30      815
    ## 17381    NA 2012-11-30      820
    ## 17382    NA 2012-11-30      825
    ## 17383    NA 2012-11-30      830
    ## 17384    NA 2012-11-30      835
    ## 17385    NA 2012-11-30      840
    ## 17386    NA 2012-11-30      845
    ## 17387    NA 2012-11-30      850
    ## 17388    NA 2012-11-30      855
    ## 17389    NA 2012-11-30      900
    ## 17390    NA 2012-11-30      905
    ## 17391    NA 2012-11-30      910
    ## 17392    NA 2012-11-30      915
    ## 17393    NA 2012-11-30      920
    ## 17394    NA 2012-11-30      925
    ## 17395    NA 2012-11-30      930
    ## 17396    NA 2012-11-30      935
    ## 17397    NA 2012-11-30      940
    ## 17398    NA 2012-11-30      945
    ## 17399    NA 2012-11-30      950
    ## 17400    NA 2012-11-30      955
    ## 17401    NA 2012-11-30     1000
    ## 17402    NA 2012-11-30     1005
    ## 17403    NA 2012-11-30     1010
    ## 17404    NA 2012-11-30     1015
    ## 17405    NA 2012-11-30     1020
    ## 17406    NA 2012-11-30     1025
    ## 17407    NA 2012-11-30     1030
    ## 17408    NA 2012-11-30     1035
    ## 17409    NA 2012-11-30     1040
    ## 17410    NA 2012-11-30     1045
    ## 17411    NA 2012-11-30     1050
    ## 17412    NA 2012-11-30     1055
    ## 17413    NA 2012-11-30     1100
    ## 17414    NA 2012-11-30     1105
    ## 17415    NA 2012-11-30     1110
    ## 17416    NA 2012-11-30     1115
    ## 17417    NA 2012-11-30     1120
    ## 17418    NA 2012-11-30     1125
    ## 17419    NA 2012-11-30     1130
    ## 17420    NA 2012-11-30     1135
    ## 17421    NA 2012-11-30     1140
    ## 17422    NA 2012-11-30     1145
    ## 17423    NA 2012-11-30     1150
    ## 17424    NA 2012-11-30     1155
    ## 17425    NA 2012-11-30     1200
    ## 17426    NA 2012-11-30     1205
    ## 17427    NA 2012-11-30     1210
    ## 17428    NA 2012-11-30     1215
    ## 17429    NA 2012-11-30     1220
    ## 17430    NA 2012-11-30     1225
    ## 17431    NA 2012-11-30     1230
    ## 17432    NA 2012-11-30     1235
    ## 17433    NA 2012-11-30     1240
    ## 17434    NA 2012-11-30     1245
    ## 17435    NA 2012-11-30     1250
    ## 17436    NA 2012-11-30     1255
    ## 17437    NA 2012-11-30     1300
    ## 17438    NA 2012-11-30     1305
    ## 17439    NA 2012-11-30     1310
    ## 17440    NA 2012-11-30     1315
    ## 17441    NA 2012-11-30     1320
    ## 17442    NA 2012-11-30     1325
    ## 17443    NA 2012-11-30     1330
    ## 17444    NA 2012-11-30     1335
    ## 17445    NA 2012-11-30     1340
    ## 17446    NA 2012-11-30     1345
    ## 17447    NA 2012-11-30     1350
    ## 17448    NA 2012-11-30     1355
    ## 17449    NA 2012-11-30     1400
    ## 17450    NA 2012-11-30     1405
    ## 17451    NA 2012-11-30     1410
    ## 17452    NA 2012-11-30     1415
    ## 17453    NA 2012-11-30     1420
    ## 17454    NA 2012-11-30     1425
    ## 17455    NA 2012-11-30     1430
    ## 17456    NA 2012-11-30     1435
    ## 17457    NA 2012-11-30     1440
    ## 17458    NA 2012-11-30     1445
    ## 17459    NA 2012-11-30     1450
    ## 17460    NA 2012-11-30     1455
    ## 17461    NA 2012-11-30     1500
    ## 17462    NA 2012-11-30     1505
    ## 17463    NA 2012-11-30     1510
    ## 17464    NA 2012-11-30     1515
    ## 17465    NA 2012-11-30     1520
    ## 17466    NA 2012-11-30     1525
    ## 17467    NA 2012-11-30     1530
    ## 17468    NA 2012-11-30     1535
    ## 17469    NA 2012-11-30     1540
    ## 17470    NA 2012-11-30     1545
    ## 17471    NA 2012-11-30     1550
    ## 17472    NA 2012-11-30     1555
    ## 17473    NA 2012-11-30     1600
    ## 17474    NA 2012-11-30     1605
    ## 17475    NA 2012-11-30     1610
    ## 17476    NA 2012-11-30     1615
    ## 17477    NA 2012-11-30     1620
    ## 17478    NA 2012-11-30     1625
    ## 17479    NA 2012-11-30     1630
    ## 17480    NA 2012-11-30     1635
    ## 17481    NA 2012-11-30     1640
    ## 17482    NA 2012-11-30     1645
    ## 17483    NA 2012-11-30     1650
    ## 17484    NA 2012-11-30     1655
    ## 17485    NA 2012-11-30     1700
    ## 17486    NA 2012-11-30     1705
    ## 17487    NA 2012-11-30     1710
    ## 17488    NA 2012-11-30     1715
    ## 17489    NA 2012-11-30     1720
    ## 17490    NA 2012-11-30     1725
    ## 17491    NA 2012-11-30     1730
    ## 17492    NA 2012-11-30     1735
    ## 17493    NA 2012-11-30     1740
    ## 17494    NA 2012-11-30     1745
    ## 17495    NA 2012-11-30     1750
    ## 17496    NA 2012-11-30     1755
    ## 17497    NA 2012-11-30     1800
    ## 17498    NA 2012-11-30     1805
    ## 17499    NA 2012-11-30     1810
    ## 17500    NA 2012-11-30     1815
    ## 17501    NA 2012-11-30     1820
    ## 17502    NA 2012-11-30     1825
    ## 17503    NA 2012-11-30     1830
    ## 17504    NA 2012-11-30     1835
    ## 17505    NA 2012-11-30     1840
    ## 17506    NA 2012-11-30     1845
    ## 17507    NA 2012-11-30     1850
    ## 17508    NA 2012-11-30     1855
    ## 17509    NA 2012-11-30     1900
    ## 17510    NA 2012-11-30     1905
    ## 17511    NA 2012-11-30     1910
    ## 17512    NA 2012-11-30     1915
    ## 17513    NA 2012-11-30     1920
    ## 17514    NA 2012-11-30     1925
    ## 17515    NA 2012-11-30     1930
    ## 17516    NA 2012-11-30     1935
    ## 17517    NA 2012-11-30     1940
    ## 17518    NA 2012-11-30     1945
    ## 17519    NA 2012-11-30     1950
    ## 17520    NA 2012-11-30     1955
    ## 17521    NA 2012-11-30     2000
    ## 17522    NA 2012-11-30     2005
    ## 17523    NA 2012-11-30     2010
    ## 17524    NA 2012-11-30     2015
    ## 17525    NA 2012-11-30     2020
    ## 17526    NA 2012-11-30     2025
    ## 17527    NA 2012-11-30     2030
    ## 17528    NA 2012-11-30     2035
    ## 17529    NA 2012-11-30     2040
    ## 17530    NA 2012-11-30     2045
    ## 17531    NA 2012-11-30     2050
    ## 17532    NA 2012-11-30     2055
    ## 17533    NA 2012-11-30     2100
    ## 17534    NA 2012-11-30     2105
    ## 17535    NA 2012-11-30     2110
    ## 17536    NA 2012-11-30     2115
    ## 17537    NA 2012-11-30     2120
    ## 17538    NA 2012-11-30     2125
    ## 17539    NA 2012-11-30     2130
    ## 17540    NA 2012-11-30     2135
    ## 17541    NA 2012-11-30     2140
    ## 17542    NA 2012-11-30     2145
    ## 17543    NA 2012-11-30     2150
    ## 17544    NA 2012-11-30     2155
    ## 17545    NA 2012-11-30     2200
    ## 17546    NA 2012-11-30     2205
    ## 17547    NA 2012-11-30     2210
    ## 17548    NA 2012-11-30     2215
    ## 17549    NA 2012-11-30     2220
    ## 17550    NA 2012-11-30     2225
    ## 17551    NA 2012-11-30     2230
    ## 17552    NA 2012-11-30     2235
    ## 17553    NA 2012-11-30     2240
    ## 17554    NA 2012-11-30     2245
    ## 17555    NA 2012-11-30     2250
    ## 17556    NA 2012-11-30     2255
    ## 17557    NA 2012-11-30     2300
    ## 17558    NA 2012-11-30     2305
    ## 17559    NA 2012-11-30     2310
    ## 17560    NA 2012-11-30     2315
    ## 17561    NA 2012-11-30     2320
    ## 17562    NA 2012-11-30     2325
    ## 17563    NA 2012-11-30     2330
    ## 17564    NA 2012-11-30     2335
    ## 17565    NA 2012-11-30     2340
    ## 17566    NA 2012-11-30     2345
    ## 17567    NA 2012-11-30     2350
    ## 17568    NA 2012-11-30     2355

    activity[is.na(activity)] <- round(average_steps, 0)

    head(activity); tail(activity)

    ##   steps       date interval
    ## 1     2 2012-10-01        0
    ## 2     0 2012-10-01        5
    ## 3     0 2012-10-01       10
    ## 4     0 2012-10-01       15
    ## 5     0 2012-10-01       20
    ## 6     2 2012-10-01       25

    ##       steps       date interval
    ## 17563     3 2012-11-30     2330
    ## 17564     5 2012-11-30     2335
    ## 17565     3 2012-11-30     2340
    ## 17566     1 2012-11-30     2345
    ## 17567     0 2012-11-30     2350
    ## 17568     1 2012-11-30     2355

    # Create a new dataset that is equal to the original dataset but with the missing data filled in.

    activity2 <- activity

    str(activity2)

    ## 'data.frame':    17568 obs. of  3 variables:
    ##  $ steps   : num  2 0 0 0 0 2 1 1 0 1 ...
    ##  $ date    : Date, format: "2012-10-01" "2012-10-01" ...
    ##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...

    head(activity2); tail(activity2)

    ##   steps       date interval
    ## 1     2 2012-10-01        0
    ## 2     0 2012-10-01        5
    ## 3     0 2012-10-01       10
    ## 4     0 2012-10-01       15
    ## 5     0 2012-10-01       20
    ## 6     2 2012-10-01       25

    ##       steps       date interval
    ## 17563     3 2012-11-30     2330
    ## 17564     5 2012-11-30     2335
    ## 17565     3 2012-11-30     2340
    ## 17566     1 2012-11-30     2345
    ## 17567     0 2012-11-30     2350
    ## 17568     1 2012-11-30     2355

    # Make a histogram of the total number of steps taken each day and calculate and report the mean and median total number of steps taken per day.

    attach(activity2)

    total_steps2 <- tapply(steps, date, sum)

    total_steps2

    ## 2012-10-01 2012-10-02 2012-10-03 2012-10-04 2012-10-05 2012-10-06 
    ##      10762        126      11352      12116      13294      15420 
    ## 2012-10-07 2012-10-08 2012-10-09 2012-10-10 2012-10-11 2012-10-12 
    ##      11015      10762      12811       9900      10304      17382 
    ## 2012-10-13 2012-10-14 2012-10-15 2012-10-16 2012-10-17 2012-10-18 
    ##      12426      15098      10139      15084      13452      10056 
    ## 2012-10-19 2012-10-20 2012-10-21 2012-10-22 2012-10-23 2012-10-24 
    ##      11829      10395       8821      13460       8918       8355 
    ## 2012-10-25 2012-10-26 2012-10-27 2012-10-28 2012-10-29 2012-10-30 
    ##       2492       6778      10119      11458       5018       9819 
    ## 2012-10-31 2012-11-01 2012-11-02 2012-11-03 2012-11-04 2012-11-05 
    ##      15414      10762      10600      10571      10762      10439 
    ## 2012-11-06 2012-11-07 2012-11-08 2012-11-09 2012-11-10 2012-11-11 
    ##       8334      12883       3219      10762      10762      12608 
    ## 2012-11-12 2012-11-13 2012-11-14 2012-11-15 2012-11-16 2012-11-17 
    ##      10765       7336      10762         41       5441      14339 
    ## 2012-11-18 2012-11-19 2012-11-20 2012-11-21 2012-11-22 2012-11-23 
    ##      15110       8841       4472      12787      20427      21194 
    ## 2012-11-24 2012-11-25 2012-11-26 2012-11-27 2012-11-28 2012-11-29 
    ##      14478      11834      11162      13646      10183       7047 
    ## 2012-11-30 
    ##      10762

    hist(total_steps2, main = "Histogram of the New Total Number of Steps Taken each Day", xlab = "New Total number of steps taken each day")

<img src="PA1_template_files/figure-markdown_strict/unnamed-chunk-4-1.png" style="display: block; margin: auto;" />

    summary(total_steps2)

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##      41    9819   10760   10770   12810   21190

    detach(activity2)

**Do these values differ from the estimates from the first part of the
assignment?**

The mean increased a little bit (9354 vs 10770) because I used the
average number of steps in order to replace the missing data; on the
other hand, the median almost remained the same (10400 vs 10760).

**What is the impact of imputing missing data on the estimates of the
total daily number of steps?**

The impact was noticeable for the mean.

Are there differences in activity patterns between weekdays and weekends?
-------------------------------------------------------------------------

    # Create a new factor variable in the dataset  with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.

    activity2$date <- weekdays(activity2$date)

    head(activity2); tail(activity2)

    ##   steps   date interval
    ## 1     2 Monday        0
    ## 2     0 Monday        5
    ## 3     0 Monday       10
    ## 4     0 Monday       15
    ## 5     0 Monday       20
    ## 6     2 Monday       25

    ##       steps   date interval
    ## 17563     3 Friday     2330
    ## 17564     5 Friday     2335
    ## 17565     3 Friday     2340
    ## 17566     1 Friday     2345
    ## 17567     0 Friday     2350
    ## 17568     1 Friday     2355

    activity2$date2[activity2$date == "Monday"] <- "weekday"

    activity2$date2[activity2$date == "Tuesday"] <- "weekday"

    activity2$date2[activity2$date == "Wednesday"] <- "weekday"

    activity2$date2[activity2$date == "Thursday"] <- "weekday"

    activity2$date2[activity2$date == "Friday"] <- "weekday"

    activity2$date2[activity2$date == "Saturday"] <- "weekend"
        
    activity2$date2[activity2$date == "Sunday"] <- "weekend"

    table(activity2$date2)

    ## 
    ## weekday weekend 
    ##   12960    4608

    str(activity2$date2)

    ##  chr [1:17568] "weekday" "weekday" "weekday" "weekday" ...

    activity2$date2 <- factor(activity2$date2)

    str(activity2$date2)

    ##  Factor w/ 2 levels "weekday","weekend": 1 1 1 1 1 1 1 1 1 1 ...

    # Make a panel plot containing a time series plot of the 5-minute interval and the average number of steps taken, averaged across all weekday or weekend days.

    weekday <- activity2[activity2$date2 == "weekday", ]

    str(weekday)

    ## 'data.frame':    12960 obs. of  4 variables:
    ##  $ steps   : num  2 0 0 0 0 2 1 1 0 1 ...
    ##  $ date    : chr  "Monday" "Monday" "Monday" "Monday" ...
    ##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...
    ##  $ date2   : Factor w/ 2 levels "weekday","weekend": 1 1 1 1 1 1 1 1 1 1 ...

    weekday_average_steps <- round(tapply(weekday$steps, weekday$interval, mean), digits = 2)

    weekday_average_steps

    ##      0      5     10     15     20     25     30     35     40     45 
    ##   2.29   0.40   0.16   0.18   0.09   1.58   0.76   1.16   0.00   1.73 
    ##     50     55    100    105    110    115    120    125    130    135 
    ##   0.36   0.00   0.38   0.13   0.18   0.40   0.00   1.44   2.24   0.00 
    ##    140    145    150    155    200    205    210    215    220    225 
    ##   0.20   0.20   0.31   0.00   0.00   0.00   1.38   0.00   0.00   0.16 
    ##    230    235    240    245    250    255    300    305    310    315 
    ##   0.00   0.27   0.00   0.00   2.09   1.24   0.00   0.00   0.00   0.00 
    ##    320    325    330    335    340    345    350    355    400    405 
    ##   0.00   0.87   1.29   0.58   0.36   0.09   0.00   0.00   0.24   1.24 
    ##    410    415    420    425    430    435    440    445    450    455 
    ##   2.29   0.00   0.40   0.00   3.36   0.27   3.71   0.91   2.33   0.71 
    ##    500    505    510    515    520    525    530    535    540    545 
    ##   0.00   2.11   3.93   2.16   4.18   2.71   2.73   7.93  20.40  23.60 
    ##    550    555    600    605    610    615    620    625    630    635 
    ##  50.29  56.20  41.22  64.56  70.11  77.09  63.93  60.02  66.42  47.93 
    ##    640    645    650    655    700    705    710    715    720    725 
    ##  55.67  54.84  47.00  60.42  50.62  50.78  62.09  69.40  63.11  59.11 
    ##    730    735    740    745    750    755    800    805    810    815 
    ##  66.27  54.31  62.69  83.44  67.76  66.56  82.67  71.93 143.96 182.04 
    ##    820    825    830    835    840    845    850    855    900    905 
    ## 200.56 183.56 198.84 230.36 218.91 185.71 191.18 177.09 167.60 125.78 
    ##    910    915    920    925    930    935    940    945    950    955 
    ##  93.93  87.29 103.58  92.47  58.49  35.82  27.49  40.89  39.13  17.62 
    ##   1000   1005   1010   1015   1020   1025   1030   1035   1040   1045 
    ##  37.93  18.22  39.02  47.87  30.36  35.18  33.09  24.20  23.56  25.87 
    ##   1050   1055   1100   1105   1110   1115   1120   1125   1130   1135 
    ##  22.02  23.27  21.64  25.13  11.64  16.33  24.13  23.67  32.71  50.20 
    ##   1140   1145   1150   1155   1200   1205   1210   1215   1220   1225 
    ##  44.56  47.98  50.11  56.11  55.73  72.89  83.67  75.31  48.67  46.80 
    ##   1230   1235   1240   1245   1250   1255   1300   1305   1310   1315 
    ##  62.51  30.69  22.04  29.36  32.78  56.56  24.56  25.76  24.53  15.64 
    ##   1320   1325   1330   1335   1340   1345   1350   1355   1400   1405 
    ##  35.60  44.80  31.80  23.29  25.24  40.24  25.53  36.36  46.96  39.56 
    ##   1410   1415   1420   1425   1430   1435   1440   1445   1450   1455 
    ##  32.18  45.09  27.42  30.82  31.51  14.58  11.53  21.98  41.91  38.31 
    ##   1500   1505   1510   1515   1520   1525   1530   1535   1540   1545 
    ##  30.87  35.04  29.89  31.93  39.87  37.38  42.11  50.89  90.58  95.91 
    ##   1550   1555   1600   1605   1610   1615   1620   1625   1630   1635 
    ##  93.93  70.31  46.87  45.18  56.67  36.11  26.82  29.56  22.53  21.89 
    ##   1640   1645   1650   1655   1700   1705   1710   1715   1720   1725 
    ##  25.91  31.93  27.60  32.47  23.62  44.91  34.22  48.04  60.16  72.38 
    ##   1730   1735   1740   1745   1750   1755   1800   1805   1810   1815 
    ##  56.16  65.87  82.87  59.40  34.53  37.53  26.69  46.62  67.27  82.60 
    ##   1820   1825   1830   1835   1840   1845   1850   1855   1900   1905 
    ##  61.36  73.49  79.27  81.47  91.67 115.40 101.36  90.64  87.58  77.24 
    ##   1910   1915   1920   1925   1930   1935   1940   1945   1950   1955 
    ##  62.38  54.33  37.84  20.60  29.04  45.98  30.02  18.64  44.31  27.36 
    ##   2000   2005   2010   2015   2020   2025   2030   2035   2040   2045 
    ##  13.44   5.56   6.78  14.07   8.73   5.69   9.73   7.11   9.02  13.07 
    ##   2050   2055   2100   2105   2110   2115   2120   2125   2130   2135 
    ##  25.93  17.29  11.38  18.87  28.44  18.91  14.22   8.04  12.84  16.47 
    ##   2140   2145   2150   2155   2200   2205   2210   2215   2220   2225 
    ##   7.18   7.62   8.24   3.49   1.47   4.47   6.33  11.22   9.27  10.89 
    ##   2230   2235   2240   2245   2250   2255   2300   2305   2310   2315 
    ##  12.82   2.87   0.00   0.13   1.96   2.07   3.51   3.76   0.00   1.11 
    ##   2320   2325   2330   2335   2340   2345   2350   2355 
    ##   1.27   1.93   3.09   2.29   2.20   0.31   0.27   1.40

    weekend <- activity2[activity2$date2 == "weekend", ]

    str(weekend)

    ## 'data.frame':    4608 obs. of  4 variables:
    ##  $ steps   : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ date    : chr  "Saturday" "Saturday" "Saturday" "Saturday" ...
    ##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...
    ##  $ date2   : Factor w/ 2 levels "weekday","weekend": 2 2 2 2 2 2 2 2 2 2 ...

    weekend_average_steps <- round(tapply(weekend$steps, weekend$interval, mean), digits = 2)

    weekend_average_steps

    ##      0      5     10     15     20     25     30     35     40     45 
    ##   0.25   0.00   0.00   0.00   0.00   3.50   0.12   0.12   0.00   0.50 
    ##     50     55    100    105    110    115    120    125    130    135 
    ##   0.00   0.44   0.00   2.38   0.00   0.00   0.00   0.12   0.75   0.56 
    ##    140    145    150    155    200    205    210    215    220    225 
    ##   0.00   0.69   0.00   0.00   0.00   0.00   0.38   0.00   0.00   0.00 
    ##    230    235    240    245    250    255    300    305    310    315 
    ##   0.00   0.00   0.00   0.00   0.25   0.12   0.00   0.00   0.00   0.00 
    ##    320    325    330    335    340    345    350    355    400    405 
    ##   0.69   0.12   2.75   0.81   0.62   0.00   0.00   0.00   3.75   0.12 
    ##    410    415    420    425    430    435    440    445    450    455 
    ##   3.56   0.00   0.00   1.19   6.19   1.94   2.62   0.69   5.25   2.19 
    ##    500    505    510    515    520    525    530    535    540    545 
    ##   0.00   0.25   0.38   2.38   0.75   3.69   0.25   0.75   3.69   3.38 
    ##    550    555    600    605    610    615    620    625    630    635 
    ##   8.75  11.31   3.88   6.12   7.94  24.88  10.69  10.62  11.94  15.00 
    ##    640    645    650    655    700    705    710    715    720    725 
    ##  11.25  14.06  10.06  17.00  24.75  26.19  18.19  12.88  12.88  28.12 
    ##    730    735    740    745    750    755    800    805    810    815 
    ##  26.06  16.06  22.81  30.69  30.06  26.81  47.06  57.62  88.38  88.81 
    ##    820    825    830    835    840    845    850    855    900    905 
    ##  88.38  76.00 116.56 138.06 131.31 162.50 161.31 138.69  75.31 119.12 
    ##    910    915    920    925    930    935    940    945    950    955 
    ## 151.75 166.62 104.25 105.81  87.81  71.56  17.31  32.88  23.31  30.69 
    ##   1000   1005   1010   1015   1020   1025   1030   1035   1040   1045 
    ##  48.19  51.62  51.75  66.31  63.06  94.81  75.62  74.38  66.19  35.12 
    ##   1050   1055   1100   1105   1110   1115   1120   1125   1130   1135 
    ##  33.69  56.38  58.50  42.62  48.38  51.69  40.12  34.12  35.25  49.38 
    ##   1140   1145   1150   1155   1200   1205   1210   1215   1220   1225 
    ##  34.94  35.31  34.56  67.75  86.81 129.50 126.38 142.00 104.62  59.56 
    ##   1230   1235   1240   1245   1250   1255   1300   1305   1310   1315 
    ##  31.62  37.06  39.38  61.44  79.56  97.31  92.19  79.69  95.81 112.25 
    ##   1320   1325   1330   1335   1340   1345   1350   1355   1400   1405 
    ##  76.06  88.94  73.69  30.25  81.38  91.19 108.44 129.69  80.62  86.88 
    ##   1410   1415   1420   1425   1430   1435   1440   1445   1450   1455 
    ##  75.88  59.00  57.88  56.69  71.00  64.12  32.75  37.56  48.62  59.25 
    ##   1500   1505   1510   1515   1520   1525   1530   1535   1540   1545 
    ##  27.62  38.94  51.00  58.38  63.12  77.06  65.00 105.75  61.38 106.56 
    ##   1550   1555   1600   1605   1610   1615   1620   1625   1630   1635 
    ## 125.06 122.38 105.00 117.38 125.06 139.19 141.56 144.88 103.94  85.69 
    ##   1640   1645   1650   1655   1700   1705   1710   1715   1720   1725 
    ##  97.56  83.25  98.44  75.38 111.50  88.19  97.25  98.19 108.19  97.44 
    ##   1730   1735   1740   1745   1750   1755   1800   1805   1810   1815 
    ## 104.94  42.38  53.19  48.62  35.56  37.00  80.19  90.06  95.75  92.81 
    ##   1820   1825   1830   1835   1840   1845   1850   1855   1900   1905 
    ##  53.25  51.81  73.44  53.81  67.38  54.38  45.25  71.62  77.31  79.56 
    ##   1910   1915   1920   1925   1930   1935   1940   1945   1950   1955 
    ##  45.81  50.44  31.88  21.19  22.56  23.25  30.62  45.19  49.62  51.12 
    ##   2000   2005   2010   2015   2020   2025   2030   2035   2040   2045 
    ##  37.19  56.88  54.50  87.38  77.75  64.62  76.56  61.19  49.38  44.38 
    ##   2050   2055   2100   2105   2110   2115   2120   2125   2130   2135 
    ##  50.06  28.12  28.81  12.50   9.19  20.06   7.25   7.94  19.94  15.69 
    ##   2140   2145   2150   2155   2200   2205   2210   2215   2220   2225 
    ##  13.06   8.38   7.75   0.38   1.19   1.62   0.62   1.12   0.88   2.69 
    ##   2230   2235   2240   2245   2250   2255   2300   2305   2310   2315 
    ##   1.25   0.25   1.06   0.00   0.81  11.94   2.56   0.38   0.00   0.12 
    ##   2320   2325   2330   2335   2340   2345   2350   2355 
    ##   0.12   0.81   1.44  11.62   6.25   1.75   0.00   0.12

    png(filename = "plot.png")

    par(mfrow = c(2,1))

    plot(interval.f, weekday_average_steps, type = "l", xlab = "5-minute interval", ylab = "Average number of steps", main = "weekdays")

    plot(interval.f, weekend_average_steps, type = "l", xlab = "5-minute interval", ylab = "Average number of steps", main = "weekends")

    dev.off()

    ## quartz_off_screen 
    ##                 2

![Time Series Plot by weekdays and
weekends](/Users/Henry/Dropbox/Education/JHU/Data%20Sience%20Specialization/5.%20Reproducible%20Research/wd_for_rr/plot.png)

**Conclusion:** Yes, there are some differences in activity patterns
between weekdays and weekends.
